export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export DOT_DIR=${DOT_DIR:-$HOME/.ilm}

source ~/.local/share/ilm/shellrc

# if interactive shell then return
[[ $- == *i* ]] || return

has_cmd ~/.local/bin/mise && eval "$(~/.local/bin/mise activate bash)"
has_cmd direnv && eval "$(direnv hook bash)"
has_cmd zoxide && eval "$(zoxide init bash)"
has_cmd fzf && source <(fzf --bash)
has_cmd starship > /dev/null && eval "$(starship init bash)"
has_cmd atuin && eval "$(atuin init bash --disable-up-arrow --disable-up-arrow)"
has_cmd pixi && eval "$(pixi completion --shell bash)"

source_if_exists ~/.local/share/ilm/fns
source_if_exists ~/.local/share/ilm/aliases

source_if_exists "$HOME/.localbashrc"
source_if_exists "$XDG_CONFIG_HOME/localbashrc"

# one_shell_tmux
