#! /usr/bin/env bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <host-ip-address>"
  exit 1
fi

nix run github:nix-community/nixos-anywhere -- \
  --flake .#generic \
  --generate-hardware-config nixos-generate-config ./hardware-configuration.nix \
  --target-host "root@${1}"
