#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    base_install
}

bootstrap "dotfiles setup"

slog "Reboot and use 'group-installer' command to install more packages"

}
