#! /usr/bin/env bash

{

DOT_DIR=$HOME/.dotfiles

BASE_URL="https://raw.githubusercontent.com/pervezfunctor/dotfiles/master"

slog() {
    printf "\r\033[2K  [ \033[00;32mINFO\033[0m ] $*\n"
}

fail() {
  printf "\r\033[2K  [ \033[0;31mFAIL\033[0m ] $*\n"
}

warn() {
    printf "\r\033[2K  [ \033[00;33mWARN\033[0m ] $*\n"
}

err_exit() {
    fail $*
    sleep 3
    exit 1
}

dir_exists() {
    [[ -d "$1" ]]
}

file_exists() {
    [[ -f "$1" ]]
}

exists() {
    [[ -e "$1" ]]
}

has_cmd() {
    command -v "$1" > /dev/null 2>&1
}

sclone() {
    local dest=${*: -1}
    local src=${*: -2:1}

    [ -d "$dest" ] && return 1

    slog "Cloning $src to $dest"
    git clone "$@"
}

fclone() {
    local dest=${*: -1}
    local src=${*: -2:1}

    srm "$dest"
    slog "Cloning $src to $dest"
    git clone "$@"
}

smv() {
    if mv "$1" "$2" 2> /dev/null; then
        slog "Moved $1 to $2"
    fi
}

smd() {
    [ -d "$1" ] && return 1

    slog "Creating directory $1"
    mkdir -p "$1" 2> /dev/null
}

fln() {
    if [ -e "$1" ]; then
        srm "$2"
    else
        warn "$1 does not exist, cannot create link $2"
        return 1
    fi
    slog "Creating link $2 to $1"
    ln -s "$1" "$2"
}

srm() {
    for f in "$@"; do
        if [ -L "$f" ]; then
            rm -f "$f" && slog "Removing link $f"
        elif has_cmd trash-put; then
            trash-put "$f" 2> /dev/null && slog "Trashed $f"
        elif has_cmd trash; then
            trash "$f" 2> /dev/null && slog "Trashed $f"
        else
            warn "trash not installed, cannot rm $f"
        fi
    done
}

frm() {
    for f in "$@"; do
        if [ -L "$f" ]; then
            rm -f "$f" && slog "Removing link $f"
        elif has_cmd trash-put; then
            trash-put "$f" 2> /dev/null && slog "Trashed $f"
        elif has_cmd trash; then
            trash "$f" 2> /dev/null && slog "Trashed $f"
        else
            warn "removing file $f"
            rm -f "$f"
        fi
    done
}

scp() {
    if [ -e "$1" ]; then
        if [ -e "$2" ]; then
            warn "$2 already exists, cannot copy $1"
        else
            slog "Copying $1 to $2"
            cp -r "$1" "$2"
        fi
    else
        warn "$1 does not exist, cannot copy to $2"
        return 1
    fi
}

fcp() {
    if [ -e "$1" ]; then
        srm "$2"
    else
        warn "$1 does not exist, cannot copy to $2"
        return 1
    fi
    slog "Copying $1 to $2"
    cp -r "$1" "$2"
}

fmv() {
    if [ -e "$1" ]; then
        srm "$2"
    else
        warn "$1 does not exist, cannot move to $2"
        return 1
    fi
    slog "Moving $1 to $2"
    mv "$1" "$2"
}

omv() {
    if [ -e "$1" ]; then
        srm "$2"
    else
        return 1
    fi

    slog "Moving $1 to $2"
    mv "$1" "$2"
}

sln() {
    if ! [ -e "$1" ]; then
        warn "$1 does not exist, cannot create the link $2"
        return 1
    elif [ -L "$2" ]; then
        srm "$2"
    elif [ -e "$2" ]; then
        warn "$2 exists and not a symbolic link! not creating link"
        return 1
    fi
    slog "Creating link $2 to $1"
    ln -s "$1" "$2"
}

spath_export() {
    dir_exists "$1" && export PATH="$1:$PATH"
}

is_mac() {
    [[ "$OSTYPE" == "darwin"* ]]
}

get_os() {
    local ID=""
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        ID=${ID:-$NAME}
    elif [ -f /etc/lsb-release ]; then
        . /etc/lsb-release
        ID=${DISTRIB_ID}
    elif [ -f /etc/redhat-release ]; then
        ID=$(awk '{print $1}' /etc/redhat-release)
    else
        ID=$(uname -s)
    fi
    echo "$ID" | tr '[:upper:]' '[:lower:]'
}

is_debian() {
    local ID
    ID=$(get_os)
    [[ "$ID" == *"debian"* ]]
}

is_suse() {
    local ID
    ID=$(get_os)
    [[ "$ID" == *"opensuse"* ]]
}

is_arch() {
    local ID
    ID=$(get_os)
    [[ "$ID" == *"arch"* ]]
}

is_wsl() {
    [ -e /proc/version ] && grep -qi microsoft /proc/version
}

is_ubuntu() {
    local ID
    ID=$(get_os)
    [[ "$ID" == *"ubuntu"* ]] || [[ "$ID" == *"neon"* ]] || [[ "$ID" == *"elementary"* ]] || [[ "$ID" == *"linuxmint"* ]] || [[ "$ID" == *"pop"* ]]
}

is_apt() {
    is_ubuntu || is_debian
}

is_fedora() {
   [ -e /etc/redhat-release ] && grep -q 'Fedora' /etc/redhat-release
}

is_kinoite() {
    [ -e /etc/os-release ] && grep -iq 'kinoite' /etc/os-release
}

is_silverblue() {
    [ -e /etc/os-release ] && grep -iq 'silverblue' /etc/os-release
}

is_atomic_fedora() {
    is_kinoite || is_silverblue
}

is_rocky() {
    [ -e /etc/redhat-release ] && grep -q 'Rocky' /etc/redhat-release
}

is_centos() {
   [ -e /etc/redhat-release ] && grep -q 'Centos' /etc/redhat-release
}

is_rh() {
    is_fedora || is_rocky || is_centos
}

is_linux() {
    [[ "$OSTYPE" == "linux-gnu" ]]
}

is_mac() {
    [[ "$OSTYPE" == "darwin"* ]]
}

fn_exists() {
    [[ $(type -t $1) == function ]]
}

pre_dir_check() {
    for dir in "$@"; do
        [ -d "$dir" ] || err_exit "$dir does not exist, quitting"
    done
}

cmd_check() {
    for cmd in "$@"; do
        has_cmd "$cmd" || warn "$cmd not installed"
    done
}

flatpak_installed() {
    flatpak list | grep -q "$1"
}

file_exists() {
     [[ -f "$1" ]]
}

dir_check() {
    for dir in "$@"; do
        dir_exists "$dir" || warn "$dir does not exist"
    done
}

cmd_check() {
    for cmd in "$@"; do
        has_cmd "$cmd" || warn "$cmd not installed"
    done
}

ln_to_exists() {
    local rl=readlink
    is_mac && rl=greadlink
    [[ "$1" == $($rl -f "$2") ]]
}

ln_check() {
    ln_to_exists "$1" "$2" || warn "$2 not a link to $1"
}

file_check() {
    for f in "$@"; do
        [ -f "$f" ] || warn "$f does not exist"
    done
}

select-one() {
    local PS3="Please enter your choice: "
    select result in "$@"; do
        if [[ -n $result ]]; then
            break
        fi
    done
    echo $result
}

keep_sudo_running() {
    slog "Keeping sudo alive"
    has_cmd sudo || err_exit "sudo must be installed"
    sudo -v
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

download_to() {
    if has_cmd curl; then
        curl -sSL "$1" -o "$2"
    elif has_cmd wget; then
        wget -nv "$1" -O "$2"
    else
        err_exit "curl or wget must be installed"
    fi
}

set_zsh_as_default() {
    slog "Setting zsh as default shell"
    chsh -s $(which zsh)
}

dotfiles_install() {
    if ! has_cmd git; then
        err_exit "git not installed, cannot clone dotfiles"
    fi

    slog "Cloning dotfiles to $DOT_DIR"
    sclone https://github.com/pervezfunctor/dotfiles.git "${DOT_DIR}"

    dir_check "$DOT_DIR"

}

stowdf() {
    for p in "$@"; do
        slog "stow $p"
        stow -d $DOT_DIR/stow -t $HOME --dotfiles -R $p
    done
}

stownf() {
    for p in "$@"; do
        slog "stow $p"
        stow --no-folding -d $DOT_DIR/stow -t $HOME --dotfiles -R $p
    done
}

source_if_exists() {
    if [[ -f "$1" ]]; then
        source "$1"
    fi
}

source_curl() {
    slog "sourcing: $1"
    source <(curl -sSL "$1")
}

sh_curl() {
    curl -sSL "$1" | bash
}


environs() {
    export PATH="/usr/bin:/snap/bin:/usr/local/go/bin:$HOME/bin:$PATH"
    export PNPM_HOME="$HOME/.local/share/pnpm"
    export PATH="$HOME/.local/bin:$PNPM_HOME:/home/linuxbrew/.linuxbrew/bin:$PATH"
    export PATH="$HOME/.local/opt/brew/bin:$PATH"
    export PATH="$XDG_CONFIG_HOME/emacs/bin:$HOME/.local/share/pypoetry:$PATH"
    export HOMEBREW_NO_ENV_HINTS=1
    export HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=1
    export HOMEBREW_NO_AUTO_UPDATE=1
}

fg-installer() {
    while [[ "$#" -gt 0 ]]; do
    if fn_exists "${1}_install"; then
        "${1}_install"
    else
        err_exit "No such installer: $1"
    fi
    shift
    done
}

bootstrap() {
    environs

    curdir=$(pwd)

    slog "Removing old logs"
    rm -f /tmp/dotfiles-error.log /tmp/dotfiles-output.log 2> /dev/null
    keep_sudo_running

    source_curl "${BASE_URL}/installers/common"

    if is_apt; then
        source_curl "${BASE_URL}/installers/apt"
    elif is_rh; then
        source_curl "${BASE_URL}/installers/dnf"
    elif is_suse; then
        source_curl "${BASE_URL}/installers/suse"
    elif is_arch; then
        source_curl "${BASE_URL}/installers/arch"
    elif is_mac; then
        source_curl "${BASE_URL}/installers/mac"
    else
        err_exit "unknown OS; skipping installation"
    fi

    slog "Installing $@ ..."
    main "$@" > >(tee /tmp/dotfiles-output.log) 2> >(tee /tmp/dotfiles-error.log >&2)
    slog "Installation done! Look at /tmp/dotfiles-error.log for any errors."

    cd "$curdir"
}

}
