
[window]
# decorations = "none"
opacity = 0.97

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[window.padding]
x = 5
y = 5

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"

[general]
# [general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 13.0
