[general]
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[window]
# decorations = "none"
opacity = 0.97

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[window.padding]
x = 5
y = 5

[font.bold]
family = "MonaspiceRn Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MonoLisaScript Nerd Font"
style = "Italic"

[font.normal]
family = "MonaspiceRn Nerd Font Mono"

[font]
size = 12.0
