#!/usr/bin/env bash

# @TODO: Make this work for alpine

function si() {
    sudo apk add --no-cache "$@"
}

update_packages() {
    slog "Updating Alpine"

    if ! { sudo apk update && sudo apk upgrade; }; then
        err_exit "apk update/upgrade failed, quitting"
    fi
}

alpine_packages() {
    sudo apk add --no-cache curl wget gcc libc-dev make gzip zsh git unzip \
        neovim tmux ripgrep luarocks fzf eza zoxide github-cli delta bat nmap \
        trash-cli starship stow just file tree fd htop sd net-tools iproute2
}

locale_setup() {
    local LOCALE KEYMAP
    LOCALE="en_US.UTF-8"
    KEYMAP="us"

    echo "$LOCALE UTF-8" >>/etc/locale.gen
    echo "LANG=$LOCALE" >/etc/locale.conf
    setup-keymap $KEYMAP # May need user interaction
}
core_install() {
    update_packages

    slog "Installing core packages"

    si gpg curl wget git trash-cli tree tar unzip stow

    slog "Core packages installation done!"
}

sys_python_install() {
    slog "Installing python"

    si python3 py3-virtualenv pipx uv

    slog "Python installation done!"

    cmd_check uv
}

essential_install() {
    slog "Installing essential packages"

    pkgx_install
    sys_python_install

    si zip micro p7zip net-tools iproute2 nmap gcc make fzf gawk just

    slog "Essential packages installation done!"
}

cli_install() {
    slog "Installing cli tools using apt"

    si tmux urlview zsh git sd gdu bat hyperfine fd ripgrep \
        zoxide eza github-cli shellcheck htop shfmt fzf ugrep starship gum \
        delta direnv yq

    slog "cli tools installation done!"
}

cpp_install() {
    slog "Installing C++"

    si libstdc++ libc6-compat python3 g++ bash emacs clang-analyzer lldb lld \
        clang-ccache clang-extra-tools llvm gcc gdb g++ catch2 clang llvm \
        clang-extra-tools ccache cppcheck pre-commit valgrind ltrace strace \
        cmake

    conan_install

    cmd_check gcc g++ gdb clang clang-tidy clang-format
    cmd_check cmake conan

    slog "C++ installation done!"
}

terminal_binstall() {
    has_cmd kitty && return 1

    slog "Installing terminal"

    si kitty

    slog "terminal installation done!"
}

vm_install() {
    si libvirt jq
    sudo systemctl enable --now libvirtd
}

incus_install() {
    has_cmd incus && return 1

    slog "Installing incus"

    si incus
    incus_confstall

    slog "incus installation done!"
}

distrobox_install() {
    has_cmd distrobox && return 1

    slog "Installing distrobox"
    si podman podman-compose buildah distrobox
    slog "distrobox installation done!"
}
