#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

pi() {
    for p in "$@"; do
        pixi global add "$p"
    done
}

pis() {
    for p in "$@"; do
        has_cmd "$p" || pixi global add "$p"
    done
}

pixi_shell_install() {
    has_cmd trash || pi trash-cli
    has_cmd || pi stow
    has_cmd rg || pi ripgrep

    pis lazygit eza fzf zoxide starship bat fd gh
}

toolbox_setup() {
    has_cmd toolbox || return 0

    toolbox --assumeyes create

    toolbox run bash -c "$(curl -sSL https://dub.sh/aPKPT8V)"
}

main() {
    has_cmd git || err_exit "git not installed! Qutting."

    dotfiles_install

    pixi_install
    has_cmd gh && github_user_setup

    mise_install

    if is_desktop; then
        smd ~/.local/share/fonts
        jetbrains_nerd_font_install
        kitty_install
        kitty_config_install
        vscode_flatpak_install
    fi
    toolbox_setup
}

is_linux || err_exit "This script is only for Linux"

bootstrap "Immutable OS"

}
