#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

gtk_cursor_theme() {
    gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
}

rpm_ostree_packages_install() {
    sudo rpm-ostree -q install -y gnome-keyring g++ cmake gcc glibc-devel make stow zsh luarocks
    # autoconf automake binutils bison flex gcc gcc-c++ gdb glibc-devel libtool make pkgconf strace
}

toolbox_setup() {
    toolbox --assumeyes create
    toolbox run sudo dnf install -y stow
    toolbox run stow -d $DOT_DIR -t $HOME --dotfiles -R share bin tmux nvim wezterm zsh
}

main() {
    has_cmd git || err_exit "git not installed! Qutting."

    dotfiles_install

    webi_install
    mise_install
    appman_install

    atomic_shell_slim_install

    smd ~/.local/share/fonts
    jetbrains_nerd_font_install

    toolbox_setup
    vscode_flatpak_install
    apps_install
}

# is_std_atomic || err_exit "This script is only for Atomic"

bootstrap "Immutable OS"

}
