#! /usr/bin/env bash

groupstall() {
    "$1"_groupstall
}

mainstall() {
    "$1"_mainstall
}

base_config_install() {
    bash_confstall
}

min_config_install() {
    base_config_install
}

shell-slim_config_install() {
    min_config_install
    git_confstall
    zsh_confstall
}

shell_config_install() {
    shell-slim_config_install
    tmux_confstall
    nvim_confstall astro
    yazi_confstall
}

shell-slim_groupstall() {
    if has_cmd cli-slim_install; then
        cli-slim_install
    else
        warn "cli-slim_install not available, skipping cli installation"
    fi

    shell-slim_install
    shell-slim_config_install
}

terminal_config_install() {
    alacritty_confstall
    kitty_confstall
    ghostty_confstall
    wezterm_confstall
}

terminal_install() {
    jetbrains-mono_install
    terminal_bin_install
}

terminal_groupstall() {
    is_desktop || return 0
    terminal_install
    terminal_config_install
}

shell_groupstall() {
    if has_cmd cli_install; then
        cli_install
    else
        warn "cli_install not available, skipping cli installation"
    fi

    shell_install
    terminal_groupstall
    shell_config_install
}

nix_groupstall() {
    nix_install
    new-hms
    # shell_config_install
}

docker_groupstall() {
    docker_bin_install
    docker_confstall
    portainer_install
}

vm_groupstall() {
    if has_cmd vm_install; then
        vm_install
    else
        warn "vm_install not available, skipping vm installation"
        return 1
    fi

    cockpit_install
    libvirt_confstall
}

bash_config_check() {
    bash_config_exists || warn "bash config is not setup correctly"
}

base_check() {
    cmd_check curl wget git trash stow tree tar unzip
    dir_check "$DOT_DIR"
    bash_config_check
}

base_main_install() {
    if has_cmd core_install; then
        core_install
    else
        warn "core_install not available, skipping core installation"
    fi

    dotfiles_install
}

base_mainstall() {
    base_main_install
    base_config_install
    base_check
}

min_check() {
    base_check
    cmd_check micro zip unar gcc make whiptail
}

min_main_install() {
    base_main_install
    if has_cmd essential_install; then
        essential_install
    else
        warn "essential_install not available, skipping essential installation"
    fi
}

min_mainstall() {
    min_main_install
    min_config_install
    min_check
}

shell-slim_check() {
    min_check
    cmd_check zsh rg starship zoxide eza gh fzf
}

shell-slim_main_install() {
    min_main_install
    shell-slim_install
}

shell-slim_mainstall() {
    shell-slim_main_install
    shell-slim_config_install
    shell-slim_check
}

nix_mainstall() {
    min_main_install
    has_cmd si && si zsh

    nix_groupstall
}

shell_check() {
    shell-slim_check
    cmd_check tmux nvim lazygit sd bat brew htop atuin gawk carapace direnv \
        shellcheck shfmt ug tldr fd direnv jq yq gum bat delta just dialog \
        btm yazi
}

shell_main_install() {
    shell-slim_main_install
    shell_install
    terminal_install
}

shell_mainstall() {
    shell_main_install
    shell_config_install
    terminal_config_install
    shell_check
}

vm_main_install() {
    min_mainstall
    vm_groupstall
}

vm_check() {
    min_check
    cmd_check virt-install virsh jq virt-cat qemu-img wget xorriso
    is_desktop && cmd_check virt-viewer virt-manager
}

vm_mainstall() {
    vm_main_install
    vm_check
}

work_check() {
    shell-slim_check
    cmd_check code docker portainer
}

work_mainstall() {
    shell-slim_mainstall
    vscode_groupstall
    docker_groupstall
    work_check
}
