#! /usr/bin/env bash

si() {
    for p in "$@"; do
        slog "Installing package $p"
        sudo dnf -q -y install "$p"
    done
}

enable_epel() {
    slog "Enabling EPEL"
    if is_rocky || is_centos; then
        sudo dnf config-manager --set-enabled crb
    fi

    is_fedora && sudo dnf-3 config-manager --set-enabled crb
    si epel-release
}

update_packages() {
    slog "Updating packages"
    if ! { sudo dnf update -q -y && sudo dnf upgrade -q -y; }; then
        err_exit "dnf update/upgrade failed, quitting"
    fi
}

fedora_packages() {
    update_packages

    si git gh git-delta unzip wget curl trash-cli tar stow \
        gcc make file just emacs-nox tree-sitter zsh tmux gum \
        tree eza fzf ripgrep zoxide fd htop sd bat tealdeer plocate cheat
}

rpm-ostree_packages() {
    sudo rpm-ostree install -q -y --apply-live \
        stow zsh tmux gcc make emacs gum fzf ripgrep wl-clipboard \
        libvirt virt-manager distrobox

    sudo systemctl enable --now libvirtd
}

centos_packages() {
    update_packages

    si git unzip wget curl tar gcc make gum tree bat ripgrep \
        htop bat plocate file just emacs-nox neovim tmux zsh
}

base_dev_install() {
    if dnf group list -q | grep -q "c-development"; then
        si @c-development
    elif dnf group list -q | grep -q "Development Tools"; then
        sudo dnf group install --setop=install_weak_deps=False --with-optional -y "Development Tools"
    else
        si gcc make cmake autoconf automake binutils expect flex bison glibc-devel
    fi
}

sys_python_install() {
    si python3 python3-virtualenv pipx python3-pip python3-setuptools python3-wheel
    pipx install uv
    pipx ensurepath
}

core_install() {
    si 'dnf-command(copr)'
    si 'dnf-command(config-manager)'
    is_fedora || enable_epel

    update_packages
    base_dev_install

    si curl wget git-core trash-cli cmake tree tar unzip
    si util-linux-user which fuse fuse-libs zstd file
    is_fedora && si stow
}

essential_install() {
    slog "Installing essential packages"

    core_install
    sys_python_install
    # mise_install
    # snap_install

    si zip p7zip cmake unar gawk
    si readline-devel sqlite-devel libffi-devel bzip2-devel xz-devel

    micro_install

    si gum

    slog "Essential packages installation done!"
}

cli_install() {
    slog "Installing cli tools using dnf"

    si zsh neovim ShellCheck tmux pkg-config urlview htop gh
    si fzf ripgrep fd-find bat plocate luarocks tealdeer zsh

    if is_fedora; then
        si python3-neovim zoxide hyperfine git-delta procs tree-sitter-cli
        si cheat navi ugrep micro direnv
    fi

    gh extension install github/gh-copilot
}

snap_install() {
    has_cmd snap && return 1

    slog "Installing snapd"
    si snapd
    sudo systemctl enable --now snapd.socket
    [ -e /snap ] || sudo ln -s /var/lib/snapd/snap /snap

    slog "snapd setup done!"
}

cpp_install() {
    slog "Installing C++"

    si gcc gcc-c++ gdb valgrind systemtap ltrace strace
    si clang clang-devel clang-tools-extra clang-libs
    si clang-analyzer lldb lld llvm llvm-devel
    si graphviz ccache cppcheck pre-commit cmake

    conan_install
    cmake_install

    if is_rocky; then
        si boost1.78 boost1.78-devel boost1.78-static catch-devel
    elif is_fedora; then
        si boost boost-devel boost-static catch-devel
        sudo dnf groupinstall -q -y --with-optional "C Development Tools and Libraries"
    fi

    slog "C++ installation done!"
}

vscode_fedora_repo() {
    has_cmd code && return 1

    [ -f /etc/yum.repos.d/vscode.repo ] && return 1

    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
}

vscode_bin_install() {
    has_cmd code && return 1

    vscode_fedora_repo

    dnf check-update
    si code code-insiders

    cmd_check code
}

terminal_bin_install() {
    has_cmd ghostty && return 1
    has_cmd kitty && return 1
    has_cmd alacritty && return 1

    if is_fedora; then
        sudo dnf copr -y enable pgdev/ghostty
        si ghostty

        cmd_check ghostty
    else
        si kitty

        if ! has_cmd kitty; then
            si alacritty
            cmd_check alacritty
        fi
    fi
}

ui_install() {
    si virt-manager chromium gnome-keyring xsel xclip wl-clipboard flatpak

    terminal_bin_install
    vscode_bin_install
    apps_install
}

cockpit_install() {
    has_cmd cockpit && return 1

    slog "Installing cockpit"
    si cockpit cockpit-machines cockpit-podman cockpit-storaged cockpit-bridge cockpit-networkmanager cockpit-selinux cockpit-system cockpit-packagekit

    si firewalld # cockpit-file-sharing
    sudo systemctl enable --now cockpit.socket
    sudo systemctl enable --now firewalld
    sudo firewall-cmd --add-service=cockpit
    sudo firewall-cmd --add-service=cockpit --permanent

    slog "cockpit installation done!"
}

docker_install() {
    has_cmd docker && return 1

    slog "Installing docker"

    si dnf-plugins-core

    is_rocky && sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    is_fedora && sudo dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    si docker-ce docker-ce-cli containerd.io docker-buildx-plugin
    si docker-compose-plugin

    docker_common_install

    slog "docker installation done!"
}

podman_install() {
    si podman podman-compose podman-tui toolbox
}

incus_install() {
    if is_centos; then
        warn "incus not available for CentOS, skipping"
        return 1
    fi

    if ! is_fedora; then
        sudo dnf -y copr enable neil/incus
    fi

    si incus
    incus_config_install
}

vm_install() {
    sudo dnf groupinstall -q -y --with-optional "System Tools"
    si libvirt buildah distrobox
    sudo systemctl enable --now libvirtd
}

ct_install() {
    incus_install
    docker_install
    portainer_install
    podman_install
    cockpit_install

    si buildah distrobox
}

virt_install() {
    ct_install
    vm_install

    code_server_install
}

more_virt_install() {
    si samba-dcerpc samba-ldb-ldap-modules samba-winbind-clients
    si samba-winbind-modules samba

    si cockpit-machines cockpit-networkmanager cockpit-system cockpit-storaged
    si cockpit-ostree cockpit-pcp cockpit-podman cockpit-selinux-compose podman-tui podmansh powertop qemu-char-spice
    si qemu-device-display-virtio-gpu qemu-device-display-virtio-vga
    si qemu-device-usb-redirect qemu-img qemu-system-x86-core qemu-user-binfmt
    si qemu-user-static qemu rocm-hip rocm-opencl udica
    si virt-manager virt-viewer libvirt

    # si containerd.io dbus-x11 docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin
    # si incus incus-agent lxc lxd-agent lxd kcli ubuntu-family-fonts
}

more_ui_install() {
    si wireguard-tools xprop solaar stress-ng usbmuxd
    si mesa-libGLU playerctl pulseaudio-utils

    if is_kde; then
        si libadwaita-qt5 libadwaita-qt6 kde-runtime-docs kdeplasma-addons
        si plasma-wallpapers-dynamic
    elif is_gnome; then
        si gnome-shell-extension-appindicator
        si gnome-shell-extension-caffeine gnome-shell-extension-dash-to-dock
        si gnome-shell-extension-gsconnect gnome-shell-extension-blur-my-shell
        # si gnome-shell-extension-search-light gnome-shell-extension-logo-menu
        si libgda libgda-sqlite
        si libratbag-ratbagd nautilus-gsconnect openssh-askpass yaru-theme
    fi

}

more_fonts_install() {
    si cascadia-code-fonts adobe-source-code-pro-fonts mozilla-fira-mono-fonts
    si jetbrains-mono-fonts-all google-go-mono-fonts ibm-plex-mono-fonts
    si google-droid-sans-mono-fonts powerline-fonts fira-code-fonts
}

more_essential_install() {
    bi glow gum
    si rclone restic wl-clipboard

    si edk2-ovmf genisoimage iotop p7zip-plugins p7zip
    si bash-color-prompt bcache-tools evtest fastfetch firewall-config
    si hplip ifuse input-remapper libimobiledevice libxcrypt-compat
}

tiling_common_install() {
    si waybar pavucontrol Thunar wl-clipboard thunar-archive-plugin
    si network-manager-applet blueman gnome-keyring-pam gnome-keyring
    si gnome-themes-extra kanshi sddm playerctl wlsunset rofi-wayland
    si rofi-themes dunst swaync lxqt-policykit network-manager-applet
    si xdg-desktop-portal-gtk pmv imv mpv wlogout qt6-qtquickcontrols2 qt6-qtsvg
    si SwayNotificationCenter
}

hyprland_bin_install() {
    tiling_common_install
    si hyprland hyprland-devel hyprutils hyprutils-devel
    si hypridle hyprpaper hyprpicker hyprlock kitty hyprcursor
}

sway_bin_install() {
    tiliing_common_install
    si sway swaybg swayidle sway-systemd swaylock sddm-wayland-sway
    si sway-config-fedora kitty
}
