#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

nvim_brewstall() {
    has_cmd nvim || bi neovim
    bis tree-sitter luarocks
}

emacs_brewstall() {
  bis emacs clang-format clang-build-analyzer llvm cmake
}

cpp_brewstall() {
  slog "Installing C++"

  bis gcc gdb cmake ccache cppcheck pre-commit clang-format
  bis strace valgrind cppcheck
  bi llvm boost catch2 clang-build-analyzer lld

  slog "C++ installation done!"
}

core_install() {
  brew_install

  bis git gh gcc make curl wget tree tar unzip stow
  has_cmd trash || bi trash-cli
}

essential_install() {
  core_install
  python_install

  bis zip unar micro cmake
}

cli_install() {
  bis zsh starship fzf fd bat zoxide eza htop tmux

  bi bash-preexec zsh-syntax-highlighting zsh-autosuggestions

  has_cmd trash || bi trash-cli
  has_cmd rg || bi ripgrep
  has_cmd delta || bi git-delta
}

shell_install() {
  cli_install
  nvim_brewstall
  emacs_brewstall
}

ct_install() {
  atomic_distrobox_install
}

vm_install() {
  appman install virtualbox

  has_cmd virt-manager && return 1

  # if has_cmd distrobox; then
  #   distrobox create -i fedora:latest --init -n virt-env
  #   distrobox enter virt-env
  #   sudo dnf install @virtualization
  #   # sudo systemctl enable --now libvirtd
  # fi
}

vscode_install() {
  has_cmd code && return 0
  has_cmd flatpak || return 1

  vscode_flatpak_install
}

ui_install() {
    kitty_install

    if !has_cmd flatpak; then
      cursor_install
      warn "flatpal not installed, skipping apps"
    fi

    flathub_install
    vscode_install
    fpi us.zoom.Zoom
    fpi md.obsidian.Obsidian
}

main() {
  essential_install
  shell_install
  ct_install
  vm_install
  ui_install
}

has_cmd git || err_exit "git not installed! Qutting."

bootstrap "generic OS"

}
