#!/usr/bin/env bash

rpm-ostree_groups_setup() {
  local -a NEEDED_GROUPS=("$@")
  local user="$USER"

  for grp in "${NEEDED_GROUPS[@]}"; do
    fix_group_for_atomic "$grp"
    add_user_to_group "$user" "$grp"
  done

  return 0
}

rpm-ostree-incus_groups_setup() {
  rpm-ostree_groups_setup incus incus-admin kvm qemu
}

rpm-ostree-libvirt_groups_setup() {
  rpm-ostree_groups_setup libvirt kvm qemu
}

rpm_installed() {
  rpm -q "$1" &>/dev/null
}

filter_packages() {
  local -a PKGS=()
  for pkg in "$@"; do
    if ! rpm_installed "$pkg"; then
      PKGS+=("$pkg")
    fi
  done

  printf "%s\n" "${PKGS[@]}"
}

core_layered() {
  filter_packages stow zsh git tmux gcc make bootc coreos-installer openssl \
    gnome-keyring wl-clipboard
}

vscode_layered() {
  if ! has_cmd code && ! file_exists /etc/yum.repos.d/vscode.repo; then
    cat <<EOF | sudo tee /etc/yum.repos.d/vscode.repo
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
EOF
  fi

  # "https://packages.microsoft.com/config/fedora/42/packages-microsoft-prod.rpm"

  filter_packages code
}

libvirt_layered() {
  filter_packages libvirt libvirt-nss virt-manager virt-install libguestfs-tools \
    guestfs-tools
}

incus_layered() {
  filter_packages qemu-kvm incus incus-agent incus-selinux incus-tools
}

layered_install() {
  local -a layers=("$@")
  local -a fns=()
  local -a PKGS=()

  for layer in "${layers[@]}"; do
    local fn="${layer}_layered"
    if fn_exists "$fn"; then
      fns+=("$fn")
    else
      warn "Layer function $fn does not exist, skipping"
    fi
  done

  while IFS= read -r pkg; do
    [[ -n "$pkg" ]] && PKGS+=("$pkg")
  done < <(
    for fn in "${fns[@]}"; do
      if ! "$fn"; then
        warn "Layer function $fn returned an error"
      fi
    done
  )

  if [[ ${#PKGS[@]} -eq 0 ]]; then
    slog "No packages to install"
    sleep 3
    return 0
  fi

  slog "Installing packages: ${PKGS[*]}"

  if ! sudo rpm-ostree install -y "${PKGS[@]}"; then
    fail "rpm-ostree install failed"
    return 1
  fi

  warn "Installing packages done! Note that you need to reboot for the changes to take effect."

  return 0
}

rpm-ostree_install() {
  has_cmd rpm-ostree || die "This script is only for rpm-ostree based systems"

  slog "Installing packages"

  mapfile -t PKGS < <(
    core_layered
    vscode_layered
    libvirt_layered
    # incus_layered
  )

  if [[ ${#PKGS[@]} -eq 0 ]]; then
    slog "No packages to install"
    sleep 3
    return 0
  fi

  if has_cmd stow || has_cmd zsh || has_cmd gcc || has_cmd make ||
    has_cmd tmux || has_cmd virsh ||
    has_cmd virt-install || has_cmd code; then
    warn "This script is supposed to be run only once"
  fi

  slog "Installing packages ${PKGS[*]}"
  sudo rpm-ostree install -y "${PKGS[@]}"

  warn "Installing packages done! Note that you need to reboot for the changes to take effect."
}

rpm-ostree-post_install() {
  vscode_confstall
  python_install

  if has_cmd virt-install; then
    rpm-ostree-libvirt_groups_setup
    sudo systemctl enable --now libvirtd
  fi
}

rpm-ostree_mainstall() {
  rpm-ostree_install
  generic_mainstall
  has_cmd homebrew-atomic && homebrew-atomic
}
