#! /usr/bin/env bash

nix_install() {
  has_cmd nix && return 0
  slog "Installing nix"

  curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --determinate --no-confirm

  # @TODO: This probable fails in distrobox
  source_if_exists /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

  slog "nix installation done!"

  cmd_check nix nix-shell nix-env
}

base_config_install() {
  dotfiles_install
  has_cmd git && git_confstall
  is_linux && bash_confstall
  is_mac && zsh_confstall
}

min_config_install() {
  base_config_install
}

shell-slim_config_install() {
  min_config_install
  zsh_confstall
}

shell_config_install() {
  shell-slim_config_install
  tmux_confstall
  nvim_confstall astro
  yazi_confstall
}

groupstall() {
  "$1"_groupstall
}

mainstall() {
  "$1"_mainstall
}

base_binstall() {
  if has_cmd core_install; then
    core_install
  else
    warn "core_install not available, skipping core installation"
  fi
}

bash_config_check() {
  bash_config_exists || warn "bash config is not setup correctly"
}

base_check() {
  cmd_check curl wget git trash stow tree tar unzip
  dir_check "$DOT_DIR"
  bash_config_check
}

base_mainstall() {
  base_binstall
  base_config_install
  base_check

  if key=$(ssh_key_path); then
    slog "SSH key at: $key"
  else
    warn "Could not generate ssh key"
  fi
}

min_binstall() {
  base_binstall
  if has_cmd essential_install; then
    essential_install
  else
    warn "essential_install not available, skipping essential installation"
  fi
  is_distrobox && return 0
  has_cmd ui_install && ui_install
}

shell-slim_binstall() {
  if has_cmd cli-slim_install; then
    cli-slim_install
  else
    warn "cli-slim_install not available, skipping cli installation"
  fi
  shell-slim_install
}

shell_binstall() {
  if has_cmd cli_install; then
    cli_install
  else
    warn "cli_install not available, skipping cli installation"
  fi

  is_distrobox || terminal_groupstall

  shell_install
  brew_install
}

shell-slim_groupstall() {
  shell-slim_binstall
  shell-slim_config_install
}

terminal_config_install() {
  alacritty_confstall
  kitty_confstall
  ghostty_confstall
  wezterm_confstall
}

terminal_groupstall() {
  if ! is_desktop; then
    warn "Not running desktop, skipping terminal installation"
    return 1
  fi

  jetbrains-mono_install
  terminal_binstall
  terminal_config_install

  is_linux && ptyxis_install
}

shell_groupstall() {
  shell_binstall
  is_distrobox || terminal_groupstall
  shell_config_install
  brew_install
}

brew_groupstall() {
  brew_install
  brew-shell_install
}

home-manager_install() {
  if ! has_cmd nix; then
    warn "nix not installed, skipping home-manager installation"
    return 1
  fi

  if dir_exists ~/nix-config; then
    slog "$HOME/nix-config exists, skipping home-manager installation"
    return 0
  fi

  if ! dir_exists "$DOT_DIR/extras/home-manager"; then
    nix_dotfiles_install
  fi

  if ! dir_exists "$DOT_DIR/extras/home-manager"; then
    warn "could not setup dotfiles, cannot install home-manager."
    return 1
  fi

  if ! cp -r "$DOT_DIR/extras/home-manager" ~/nix-config; then
    warn "Failed to copy home-manager config to $HOME/nix-config"
    return 1
  fi

  nix-vars-create "$HOME/nix-config/vars.nix"

  slog "nix-config copied to $HOME/nix-config. Running hms to apply configuration."

  hms

  return 0
}

nix_groupstall() {
  nix_install
  home-manager_install
}

nix_check() {
  min_check
  cmd_check home-manager nix devbox
}

nix_mainstall() {
  min_mainstall
  has_cmd si && (has_cmd zsh || si zsh)
  nix_groupstall shell
  nix_check
}

docker_groupstall() {
  docker_install

  is_linux || return 0
  is_distrobox || fpi sh.loft.devpod
  docker_confstall
  lazydocker_install
}

work_groupstall() {
  shell-slim_groupstall
  vscode_groupstall
  docker_groupstall
}

vm_groupstall() {
  if has_cmd vm_install; then
    vm_install
  else
    warn "vm_install not available, skipping vm installation"
    return 1
  fi

  if ! is_distrobox; then
    has_cmd vm-ui_install && vm-ui_install
  fi

  is_linux || return 0

  cockpit_install
  libvirt_confstall
  has_cmd osinfo-db-import && sudo osinfo-db-import --system --latest
}

min_check() {
  base_check
  cmd_check micro zip gcc make whiptail
}

min_mainstall() {
  min_binstall
  min_config_install
  min_check
}

shell-slim_check() {
  min_check
  cmd_check zsh rg starship zoxide eza gh fzf
}

shell-slim_mainstall() {
  min_binstall
  shell-slim_binstall
  shell-slim_config_install
  shell-slim_check
}

shell_check() {
  shell-slim_check
  cmd_check tmux nvim lazygit sd bat htop atuin gawk carapace direnv \
    shellcheck shfmt ug tldr fdfind direnv jq yq gum bat delta just dialog \
    btm yazi
}

shell_mainstall() {
  min_binstall
  shell_binstall
  shell_config_install
  terminal_config_install
  shell_check
}

vm_check() {
  min_check

  if is_linux; then
    cmd_check virt-install virt-xml virsh jq virt-cat qemu-img wget xorriso
    is_desktop && cmd_check virt-viewer virt-manager
  elif is_mac; then
    cmd_check jq colima orbstack
  fi
}

vm_mainstall() {
  min_mainstall
  vm_groupstall
  vm_check
}

work_check() {
  shell-slim_check
  cmd_check code docker
}

work_mainstall() {
  min_mainstall
  work_groupstall
  apps-slim_install
  work_check
}

desktop-slim_mainstall() {
  shell-slim_mainstall
  vm_groupstall
  vscode_groupstall

  apps-slim_install

  vm_check
  work_check
}

desktop_mainstall() {
  shell_mainstall
  vm_groupstall
  vscode_groupstall

  apps_install

  vm_check
  work_check
}
