#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

distrobox_setup() {
    has_cmd distrobox || distrobox_install

    has_cmd nix || return 0

    source_curl "$DOT_DIR/share/fns"
    dbox_nix
}

toolbox_setup() {
    has_cmd toolbox || return 0

    toolbox create --assumeyes
    toolbox run bash -c "$(curl -sSL https://dub.sh/aPKPT8V)" -- shell
}

main() {
    if ! has_cmd git; then
        if has_cmd nix; then
           nix run nixpkgs#git clone https://github.com/pervezfunctor/dotfiles.git "${DOT_DIR}"
        fi
        has_cmd git || err_exit "git not installed! Qutting."
    fi

    dotfiles_install

    mise_install

    starship_install
    bash_config_install

    if is_desktop; then
        jetbrains_nerd_font_install

        has_cmd flatpak || return 0

        flathub_install
        vscode_flatpak_install
        fpi app.devsuite.Ptyxis
        fpi io.github.getnf.embellish

        has_cmd gsettings && gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
    fi

    toolbox_setup
}

is_linux || err_exit "This script is only for Linux"

export NOSUDO=1

bootstrap "Linux OS"

}
