#!/usr/bin/env bash

# shellcheck disable=SC1091
# shellcheck disable=SC1090

set -euo pipefail

DOT_DIR="${DOT_DIR:-$HOME/.ilm}"

source "$DOT_DIR/share/utils"

source_installers &>/dev/null

if file_exists "$1"; then
  source "$1"
else
  err_exit "script $1 not found"
fi

cmd_check core_install
cmd_check essential_install

cmd_check cli-slim_install
cmd_check cli_install
cmd_check cpp_install
cmd_check vscode_binstall
cmd_check terminal_binstall
cmd_check emacs_binstall
cmd_check ui_install
cmd_check vm_install

if ! is_atomic && ! is_mac; then
  cmd_check docker_install
  cmd_check distrobox_install
  cmd_check incus_install
  cmd_check vm-ui_install
fi

cmd_check dotfiles_install
cmd_check pkgx_install
cmd_check docker_install
cmd_check pixi_install
cmd_check brew_install
cmd_check pixi-shell_slim_install
cmd_check brew-shell_slim_install
cmd_check pixi-shell_install
cmd_check brew-shell_install
cmd_check vscode_groupstall
cmd_check python_install
cmd_check shell_install

if ! is_mac; then
  cmd_check fonts_install
  cmd_check starship_install
  cmd_check flathub_install
  cmd_check atomic_distrobox_install
  cmd_check apps_install
  cmd_check slim-apps_install
  cmd_check gnome_confstall

  cmd_check incus_confstall
  cmd_check libvirt_confstall
  cmd_check docker_confstall
fi

cmd_check git_confstall
cmd_check bash_confstall
cmd_check zsh-min_confstall
cmd_check zsh_confstall
cmd_check ghostty_confstall
cmd_check wezterm_confstall
cmd_check kitty_confstall
cmd_check tmux_confstall
cmd_check emacs_confstall
cmd_check nvim_confstall

cmd_check generic_mainstall

is_atomic && return 0

cmd_check base_mainstall
cmd_check min_mainstall
cmd_check shell-slim_mainstall
cmd_check shell_mainstall
cmd_check vm_mainstall

cmd_check nvim_boxstall
cmd_check emacs_boxstall
cmd_check tmux_boxstall
cmd_check zsh_boxstall
cmd_check terminal_boxstall

cmd_check slimbox_mainstall
cmd_check box_mainstall
cmd_check terminal_boxstall
cmd_check dbox_mainstall
cmd_check wslbox_mainstall
cmd_check wsl_mainstall
cmd_check wsl_mainstall
cmd_check centos-wsl_mainstall
cmd_check nixbox_mainstall
cmd_check nixos-wslbox_mainstall
cmd_check fullbox_mainstall
