#!/usr/bin/env bash

if [ -z "$BASH_VERSION" ]; then
  echo "This script must be run with bash."
  exit 0
fi

if ((BASH_VERSINFO[0] < 5)); then
  echo "❌ Bash version 5.x or higher is required."
  exit 1
fi

if command -v curl &>/dev/null; then
  # shellcheck disable=SC1090
  source <(curl -sSL https://raw.githubusercontent.com/pervezfunctor/dotfiles/refs/heads/main/share/utils)
elif command -v wget &>/dev/null; then
  # shellcheck disable=SC1090
  source <(wget -qO- https://raw.githubusercontent.com/pervezfunctor/dotfiles/refs/heads/main/share/utils)
else
  echo "curl or wget is not installed"
  exit 1
fi

main() {
  if has_cmd "${1}_mainstall"; then
    "${1}_mainstall"
    shift 1
  else
    if has_cmd min_mainstall; then
      min_mainstall
    else
      die "unknown or unsupported $* options"
    fi
  fi
  common_installer "$@"

  if has_cmd zsh && [ "$(default_shell)" != "zsh" ]; then
    set_zsh_as_default
    zsh_confstall
  fi
}

if [[ "$1" == "generic" ]] ||
  [[ "$1" == "generic-ct" ]] ||
  [[ "$1" == "fedora-atomic" ]] ||
  is_proxmox ||
  is_ublue ||
  is_multipass ||
  is_distrobox; then
  export NOSUDO=1
fi

bootstrap "$@"
