#! /usr/bin/env bash

{

command -v curl > /dev/null || err_exit "Install curl before running this script"

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    has_cmd git || err_exit "Install git before running this script"

    if is_linux && has_cmd python3; then
        python_install
        pipx install trash-cli
    fi

    if is_mac; then
        brew_install
    else
        appman_install
    fi

    mise_install

    if is_linux; then
        slog "Installing shell tools"

        mis tree-sitter just lazygit starship ripgrep xh
        mis bottom fzf fd eza zoxide bat duf
        mise use -g cargo:git-delta
        ami sd nvim tmux gh

        slog "shell tools installation done!"

        if has_cmd flatpak; then
            slog "Setting up shell for desktop"
            smd ~/.local/share/fonts
            jetbrains_nerd_font_install

            flathub_install
            ptyxis_install
            slog "Shell setup for desktop done!"
        fi
    elif is_mac; then
        slog "Installing shell tools"

        bis tree-sitter just lazygit starship gh xh git-delta sd trash-cli

        if ! has_cmd luarocks; then
            bi luarocks
            brew link luarocks
        fi

        bis fzf fd eza zoxide bat tmux duf
        bi bottom ripgrep neovim reattach-to-user-namespace
        bi

        bic wezterm font-jetbrains-mono-nerd-font

        slog "shell tools installation done!"
    fi

    cmd_check tree-sitter just starship rg gh xh btm fzf fd eza zoxide bat tmux duf delta sd nvim

    gh extension install github/gh-copilot

    dotfiles_install
    shell_config_install
}

is_linux || is_mac || err_exit "This script is only for Linux and Mac"

bootstrap "Shell/Terminal setup"

}
