#!/usr/bin/env bash

# shellcheck disable=SC1090
source <(curl -sSL https://is.gd/anumof) || err_exit "Cannot source utils, Quitting"

ublue_emacs_setup() {
    slog "emacs installation and setup"

    bis emacs
    bi emacs-clang-complete-async
    srm ~/.emacs
    srm ~/.emacs.d
    srm "$XDG_CONFIG_HOME/emacs"
    stowdf emacs-slim # or emacs

    slog "emacs installation done!"
}

ublue_cpp_setup() {
    slog "Installing C++ tools"

    bi llvm lld
    bis clang-format cmake

    slog "C++ installation done!"
}

config_setup() {
    if ! dir_exists "$DOT_DIR"; then
        warn "$DOT_DIR doesn't exist, skipping configuration"
        return 1
    fi

    if ! has_cmd stow; then
        warn "stow not installed, skipping configuration"
        return 1
    fi

    slog "config setup"

    bash_confstall
    zsh_confstall
    tmux_confstall

    slog "config setup done!"
}

ublue_cli_install() {
    is_bluefin && ujust bluefin-cli
    is_aurora && ujust aurora-cli
    is_bazzite && ujust bazzite-cli
}

main() {
    dotfiles_install
    python_install
    brew-shell-slim_install
    apps-slim_install

    vscode_confstall
    jetbrains-mono_install
    config_setup
    is_gnome && gnome_confstall

    if [[ "$USER" == "pervez" ]]; then
        slog "Setting up ublue for myself"
        ublue_cpp_setup
        ublue_emacs_setup
        nvim_confstall astro
        git_confstall
        ublue_cli_install
    fi
}

if is_ublue && has_cmd git && has_cmd brew && has_cmd python3 && has_cmd code && has_cmd flatpak && has_cmd distrobox; then
    export NOSUDO=1
    bootstrap "uBlue OS"
else
    err_exit "Prerequisites not met. You need Aurora/Bluefin with git, just, brew, code, flatpak, distrobox and python3 installed."
fi
