#! /usr/bin/env bash

{

si() {
    for p in "$@"; do
        slog "Installing package $p"
        sudo zypper --non-interactive --quiet install --auto-agree-with-licenses "$p"
    done
}

update_packages() {
    slog "Updating"

    if ! { sudo zypper refresh && sudo zypper --non-interactive --quiet dup; }; then
        err_exit "zypper refresh failed. quitting"
    fi
}

sys_python_install() {
    si python3 python3-virtualenv python3-pip python3-setuptools
}

core_install() {
    update_packages

    si curl wget git tar tree zsh unzip unar zip micro-editor python311-pipx
    sudo zypper install -y -t pattern devel_basis
    pipx install trash-cli
}

snap_install() {
    has_cmd snap && return 0

    slog "Installing snap..."

    sudo zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed snappy
    sudo zypper --gpg-auto-import-keys refresh
    sudo zypper dup --from snappy

    slog "snap installation done!"
}

essential_install() {
    slog "Installing essential packages"

    core_install

    si gawk tmux urlview 7zip cmake
    si readline-devel sqlite3-devel libffi-devel libbz2-devel xz-devel

    sys_python_install

    webi_install
    webi brew pathman

    snap_install

    slog "Essential packages installation done!"
}

cli_install() {
    si gh ShellCheck shfmt neovim tree-sitter
    gh extension install github/gh-copilot
    si lazygit bottom sd lsd bat hyperfine fd fzf ripgrep zoxide cheat
    si curlie git-delta jq duf lua54-luarocks python3-neovim
}

cpp_install() {
    slog "Installing C++"

    si gcc gdb g++ boost-devel catch2-devel
    si clang llvm clang-tools clang-devel
    si doxygen graphviz ccache cppcheck python3-pre-commit
    si valgrind systemtap ltrace strace lldb lld

    cmake_install
    conan_install

    slog "C++ installation done!"
}

vscode_install() {
    has_cmd code && return 0

    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/zypp/repos.d/vscode.repo'
    sudo zypper refresh
    si code
}

ui_install() {
    si chromium-browser virt-manager gnome-keyring xsel xclip wl-clipboard
    vscode_install
    flathub_install
    flatpak_apps_install
}

cockpit_install() {
    has_cmd cockpit && return 1

    slog "Installing cockpit"

    si systemd-network
    si cockpit cockpit-machines cockpit-pcp cockpit-podman cockpit-storaged cockpit-kdump cockpit-networkmanager cockpit-packagekit cockpit-system cockpit-tukit
    # microos_cockpit patterns-microos-cockpit
    sudo systemctl enable --now cockpit.socket

    slog "cockpit installation done!"
}

podman_install() {
    si podman podman-remote
}

libvirt_install() {
    si buildah libvirt-daemon distrobox

    sudo systemctl enable --now libvirtd
}

docker_install() {
    si docker docker-compose docker-compose-switch
    docker_common_install
}

ct_install() {
    docker_install
    podman_install
    si buildah distrobox
    cockpit_install
}

virt_install() {
    libvirt_install
    ct_install
    code_server_install
}

}
