#! /usr/bin/env bash

{

si() {
    for p in "$@"; do
        slog "Installing package $p"
        sudo zypper install -y "$p"
    done
}

update_packages() {
    slog "Updating"

    if ! { sudo zypper refresh && sudo zypper dup -y; }; then
        err_exit "zypper refresh failed. quitting"
    fi
}

core_install() {
    si curl wget git tar tree zsh unzip unar 7zip zip gh
}

sys_python_install() {
    si python3-pip python3-virtualenv
    si python311-pipx
    pipx install trash-cli
    # python3 -m pip install --user --upgrade pip setuptools
}

essential_install() {
    update_packages

    slog "Installing essential packages"

    core_install

    si tmux urlview fasd ShellCheck shfmt xclip xsel micro-editor
    sys_python_install
    webi_install
    webi brew pathman

    si sd lsd bat hyperfine fd fzf ripgrep zoxide cheat curlie git-delta jq duf

    slog "Essential packages installation done!"
}

flathub_install() {
    si flatpak
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo --user
}

cpp_install() {
    slog "Installing C++"

    si gcc gdb g++ boost-devel catch2-devel
    si clang llvm clang-tools clang-devel
    si doxygen graphviz ccache cppcheck python3-pre-commit
    si valgrind systemtap ltrace strace lldb lld

    cmake_install
    conan_install

    slog "C++ installation done!"
}

vscode_install() {
    has_cmd code && return 0


    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/zypp/repos.d/vscode.repo'
    sudo zypper refresh
    si code
}

apps_install() {
    si chromium-browser virt-manager
    flatpak_apps_install
}

snap_install() {
    has_cmd snap && return 0

    slog "Installing snap..."

    sudo zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed snappy
    sudo zypper --gpg-auto-import-keys refresh
    sudo zypper dup --from snappy

    slog "snap installation done!"
}

cockpit_install() {
    has_cmd cockpit && return 1

    slog "Installing cockpit"

    si cockpit cockpit-machines cockpit-pcp cockpit-podman cockpit-storaged cockpit-kdump cockpit-networkmanager cockpit-packagekit cockpit-system cockpit-tukit
    # microos_cockpit patterns-microos-cockpit
    sudo systemctl enable --now cockpit.socket

    slog "cockpit installation done!"
}

podman_install() {
    si podman podman-remote
}

libvirt_install() {
    si buildah libvirt-daemon distrobox

    sudo systemctl enable --now libvirtd
}

ct_install() {
    docker_install
    podman_install
    cockpit_install
}

virt_install() {
    ct_install
    libvirt_install
    code_server_install
}

}
