#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)


main() {
    essential_install
    dotfiles_install

    pnpm_install

    fonts_install

    vscode_install
    ui_install

    config_install

    set_zsh_as_default
}

is_suse || err_exit "This script works only on Fedora. Quitting."

bootstrap "Suse desktop setup(desktop)"

}
