#! /usr/bin/env bash

cat <<EOF | sudo tee /etc/modprobe.d/blacklist-vfio.conf
blacklist nouveau
blacklist radeon
blacklist amdgpu
blacklist i915
blacklist snd_hda_intel
EOF

sudo update-initramfs -u -k all
