#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    sudo rpm-ostree install zsh gcc cmake trash-cli
    dotfiles_install

    config_install

    set_zsh_as_default

    tool
}

is_atomic_fedora || err_exit "This script works only on Fedora/RockyLinux. Quitting."

bootstrap "Fedora/RockyLinux setup(min)"

}
