#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    dotfiles_install
    essential_install

    go_install
    rust_install
    pnpm_install

    shell_install

    neovim_install

    cli_config

    dnfi util-linux-user
    set_zsh_as_default
}

is_rocky|| err_exit "This installer works only on Rocky Linux. Quitting."

bootstrap "Rocky Linux development system"

}
