#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    essential_install
    dotfiles_install

    cpp_install
    python_install
    config_install

    si util-linux-user
    set_zsh_as_default
}

is_rocky|| err_exit "This installer works only on Rocky Linux. Quitting."

bootstrap "Rocky Linux development system(cloud)"

}
