#! /usr/bin/env bash

{

si() {
    for p in "$@"; do
    slog "Installing package $p"
        sudo dnf -y install "$p"
    done
}

enable_epel() {
    slog "Enabling EPEL"
    sudo dnf config-manager --set-enabled crb
    si epel-release
}

update_packages() {
    slog "Updating packages"
    if ! { sudo dnf update -y && sudo dnf upgrade -y; }; then
        err_exit "dnf update/upgrade failed, quitting"
    fi
}

core_install() {
    si 'dnf-command(copr)'
    si 'dnf-command(config-manager)'

    si curl wget git trash-cli tree tar unar zip unzip p7zip gawk
    si zsh zsh-syntax-highlighting zsh-autosuggestions
}

sys_python_install() {
    si python3-pip python3-virtualenv python3-wheel pipx
}

essential_install() {
    is_fedora || enable_epel

    slog "Installing essential packages"

    core_install

    si tmux pkg-config urlview neovim ShellCheck git-extras
    si xclip xsel sqlite-devel

    si git-delta procs fzf ripgrep fd-find hyperfine bat zoxide

    sys_python_install
    micro_install
    gh_install

    webi_install

    slog "Essential packages installation done!"
}

snap_install() {
    has_cmd snap && return 1

    slog "Installing snapd"
    si snapd
    sudo systemctl enable --now snapd.socket
    [ -e /snap ] || sudo ln -s /var/lib/snapd/snap /snap
    sleep 5

    sudo snap install fasd --beta

    slog "snapd setup done!"
}

flathub_install() {
    has_cmd flatpak || return 1
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo --user
}

lazygit_install() {
    has_cmd lazygit && return 1

    slog "Installing lazygit"
    sudo dnf copr enable atim/lazygit -y
    si lazygit

    slog "lazygit installation done!"
}

gdu_install() {
    has_cmd gdu && return 1

    slog "Installing gdu"
    sudo dnf copr enable copr.fedorainfracloud.org/faramirza/gdu -y
    si gdu
    slog "gdu installation done!"
}

gh_install() {
    has_cmd gh && return 1

    slog "Installing up gh"

    sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
    si gh

    slog "gh setup done!"
}

cpp_install() {
    slog "Installing C++"

    sudo dnf groupinstall "Development Tools" -y
    si gcc gcc-c++ gdb valgrind systemtap ltrace strace
    si clang clang-devel clang-tools-extra clang-libs
    si clang-analyzer lldb lld llvm llvm-devel
    si graphviz ccache cppcheck pre-commit

    conan_install
    cmake_install

    if is_rocky; then
        si boost1.78 boost1.78-devel boost1.78-static catch-devel
    elif is_fedora; then
        si boost boost-devel boost-static catch-devel
        sudo dnf groupinstall -y --with-optional "C Development Tools and Libraries"
    fi

    slog "C++ installation done!"
}

vscode_install() {
    has_cmd code && return 1

    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    dnf check-update
    si code code-insiders
}

apps_install() {
    si virt-manager chromium neovim emacs
    flatpak_apps_install
}

cockpit_install() {
    has_cmd cockpit && return 1

    slog "Installing cockpit"

    si cockpit cockpit-file-sharing cockpit-machines cockpit-pcp cockpit-podman cockpit-storaged firewalld
    sudo systemctl enable --now cockpit.socket
    sudo systemctl enable --now firewalld
    sudo firewall-cmd --add-service=cockpit
    sudo firewall-cmd --add-service=cockpit --permanent

    slog "cockpit installation done!"
}

docker_install() {
    has_cmd docker && return 1

    slog "Installing docker"

    si dnf-plugins-core

    is_rocky && sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    is_fedora && sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    si docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    docker_common_install

    slog "docker installation done!"
}

podman_install() {
    si podman toolbox
}

libvirt_install() {
    sudo dnf groupinstall -y --with-optional "System Tools"

    si libvirt buildah distrobox

    sudo systemctl enable --now libvirtd
}

ct_install() {
    docker_install
    podman_install
    cockpit_install
}

virt_install() {
    ct_install
    libvirt_install
    code_server_install
}

}
