#! /usr/bin/env bash

{

si() {
    for p in "$@"; do
        slog "Installing package $p"
        sudo dnf -q -y install "$p"
    done
}

enable_epel() {
    slog "Enabling EPEL"
    sudo dnf config-manager --set-enabled crb
    si epel-release
}

update_packages() {
    slog "Updating packages"
    if ! { sudo dnf update -q -y && sudo dnf upgrade -q -y; }; then
        err_exit "dnf update/upgrade failed, quitting"
    fi
}

core_install() {
    is_fedora || enable_epel
    si 'dnf-command(copr)'
    si 'dnf-command(config-manager)'

    update_packages

    si curl wget git-core trash-cli tree tar unzip which util-linux-user
}

sys_python_install() {
    si python3 python3-virtualenv pipx python3-pip python3-setuptools python3-wheel
    pipx install uv
}

base_dev_install() {
    if dnf group list -q | grep -q "c-development"; then
        si @c-development
    elif dnf group list -q | grep -q "Development Tools"; then
        sudo dnf group install --setop=install_weak_deps=False --with-optional -y "Development Tools"
    else
        si gcc make cmake autoconf automake binutils expect flex bison glibc-devel
    fi
}

essential_install() {
    slog "Installing essential packages"

    core_install

    si gawk tmux pkg-config urlview zip p7zip cmake unar zsh
    si readline-devel sqlite-devel libffi-devel bzip2-devel xz-devel

    micro_install
    base_dev_install
    sys_python_install

    webi_install
    mise_install
    brew_install

    si gum

    snap_install

    slog "Essential packages installation done!"
}

cli_install() {
    si neovim ShellCheck python3-neovim
    webi curlie lsd shfmt gh lazygit
    gh extension install github/gh-copilot
    si git-delta procs fzf ripgrep fd-find hyperfine bat zoxide

    brew install -q gdu
    alias gdu=gdu-go
}

snap_install() {
    has_cmd snap && return 1

    slog "Installing snapd"
    si snapd
    sudo systemctl enable --now snapd.socket
    [ -e /snap ] || sudo ln -s /var/lib/snapd/snap /snap

    slog "snapd setup done!"
}

cpp_install() {
    slog "Installing C++"

    si gcc gcc-c++ gdb valgrind systemtap ltrace strace
    si clang clang-devel clang-tools-extra clang-libs
    si clang-analyzer lldb lld llvm llvm-devel
    si graphviz ccache cppcheck pre-commit

    conan_install
    cmake_install

    if is_rocky; then
        si boost1.78 boost1.78-devel boost1.78-static catch-devel
    elif is_fedora; then
        si boost boost-devel boost-static catch-devel
        sudo dnf groupinstall -q -y --with-optional "C Development Tools and Libraries"
    fi

    slog "C++ installation done!"
}

vscode_install() {
    has_cmd code && return 1

    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    dnf check-update
    si code code-insiders
}

ghostty_install() {
    has_cmd ghostty && return 1

    sudo dnf copr -y enable pgdev/ghostty
    si ghostty
}

ui_install() {
    vscode_install
    si virt-manager chromium gnome-keyring xsel xclip wl-clipboard
    flathub_install
    ghostty_install
    flatpak_apps_install
}

cockpit_install() {
    has_cmd cockpit && return 1

    slog "Installing cockpit"

    si cockpit cockpit-machines cockpit-pcp cockpit-podman cockpit-storaged firewalld # cockpit-file-sharing
    sudo systemctl enable --now cockpit.socket
    sudo systemctl enable --now firewalld
    sudo firewall-cmd --add-service=cockpit
    sudo firewall-cmd --add-service=cockpit --permanent

    slog "cockpit installation done!"
}

docker_install() {
    has_cmd docker && return 1

    slog "Installing docker"

    si dnf-plugins-core

    is_rocky && sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    is_fedora && sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

    si docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    docker_common_install

    slog "docker installation done!"
}

podman_install() {
    si podman podman-compose podman-tui toolbox
}

incus_install() {
    if ! is_fedora; then
        sudo dnf -y copr enable neil/incus

    fi

    si incus
    incus_config_install
}

libvirt_install() {
    sudo dnf groupinstall -q -y --with-optional "System Tools"
    si libvirt buildah distrobox
    sudo systemctl enable --now libvirtd
}

ct_install() {
    incus_install
    docker_install
    podman_install
    si buildah distrobox
    cockpit_install
}

virt_install() {
    ct_install
    libvirt_install
    code_server_install
}

}
