#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)


more_essential_install() {
    brew install -q glow gum

    si rclone restic wl-clipboard
    si cascadia-code-fonts adobe-source-code-pro-fonts mozilla-fira-mono-fonts
    si jetbrains-mono-fonts-all google-go-mono-fonts ibm-plex-mono-fonts
    si google-droid-sans-mono-fonts powerline-fonts

    si edk2-ovmf genisoimage iotop p7zip-plugins p7zip
    si wireguard-tools xprop solaar stress-ng usbmuxd

    si bash-color-prompt bcache-tools evtest fastfetch firewall-config
    si hplip ifuse input-remapper libimobiledevice libxcrypt-compat
    si mesa-libGLU playerctl pulseaudio-utils

    si samba-dcerpc samba-ldb-ldap-modules samba-winbind-clients
    si samba-winbind-modules samba

    si cockpit-machines cockpit-networkmanager cockpit-system
    si cockpit-ostree cockpit-pcp cockpit-podman cockpit-selinux cockpit-storaged
    si podman-compose podman-tui podmansh powertop qemu-char-spice
    si qemu-device-display-virtio-gpu qemu-device-display-virtio-vga
    si qemu-device-usb-redirect qemu-img qemu-system-x86-core qemu-user-binfmt
    si qemu-user-static qemu rocm-hip rocm-opencl udica
    si virt-manager virt-viewer libvirt

    # si code containerd.io dbus-x11 docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin
    # si incus incus-agent lxc lxd-agent lxd kcli ubuntu-family-fonts

    if is_kde; then
        si libadwaita-qt5 libadwaita-qt6 kde-runtime-docs kdeplasma-addons plasma-wallpapers-dynamic
    else is_gnome; then
        si gnome-shell-extension-appindicator gnome-shell-extension-blur-my-shell
        si gnome-shell-extension-caffeine gnome-shell-extension-dash-to-dock
        si gnome-shell-extension-gsconnect
        # si gnome-shell-extension-search-light gnome-shell-extension-logo-menu
        si libgda libgda-sqlite
        si libratbag-ratbagd nautilus-gsconnect openssh-askpass yaru-theme
    fi
}

main() {
    essential_install
    dotfiles_install

    flathub_install

    go_install
    rust_install
    pnpm_install

    fonts_install

    cpp_install
    python_install

    shell_install

    vscode_install
    ui_install

    virt_install

    config_install

    set_zsh_as_default
}

is_fedora || err_exit "This script works only on Fedora. Quitting."

bootstrap "Fedora desktop setup(desktop)"

}
