#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)


more_essential_install() {
    si bash-color-prompt bcache-tools evtest fastfetch firewall-config gcc glow
    si gum hplip ifuse input-remapper libimobiledevice libxcrypt-compat make
    si mesa-libGLU nerd-fonts playerctl pulseaudio-utils python3-pip rclone
    si restic samba-dcerpc samba-ldb-ldap-modules samba-winbind-clients
    si samba-winbind-modules samba solaar stress-ng tailscale tmux usbmuxd
    si wireguard-tools xprop wl-clipboa adobe-source-code-pro-fonts
    si cascadia-code-fonts cockpit-machines cockpit-networkmanager cockpit-system
    si cockpit-ostree cockpit-pcp cockpit-podman cockpit-selinux cockpit-storaged
    si code containerd.io dbus-x11 docker-ce docker-ce-cli docker-buildx-plugin
    si docker-compose-plugin edk2-ovmf genisoimage google-droid-sans-mono-fonts
    si google-go-mono-fonts ibm-plex-mono-fonts incus incus-agent iotop
    si jetbrains-mono-fonts-all kcli libvirt lxc lxd-agent lxd
    si mozilla-fira-mono-fonts p7zip-plugins p7zip podman-compose podman-tui
    si podmansh powerline-fonts powertop qemu-char-spice
    si qemu-device-display-virtio-gpu qemu-device-display-virtio-vga
    si qemu-device-usb-redirect qemu-img qemu-system-x86-core qemu-user-binfmt
    si qemu-user-static qemu rocm-hip rocm-opencl ubuntu-family-fonts udica
    si virt-manager virt-viewer

    if is_kde; then
        si libadwaita-qt5 libadwaita-qt6 de-runtime-docs kdeplasma-addons plasma-wallpapers-dynamic
    else is_gnome; then
        si gnome-shell-extension-appindicator gnome-shell-extension-blur-my-shell
        si gnome-shell-extension-caffeine gnome-shell-extension-dash-to-dock
        si gnome-shell-extension-gsconnect gnome-shell-extension-logo-menu
        si gnome-shell-extension-search-light libgda-sqlite libgda
        si libratbag-ratbagd nautilus-gsconnect openssh-askpass yaru-theme
    fi
}

main() {
    dotfiles_install
    essential_install

    flathub_install

    go_install
    rust_install
    pnpm_install

    fonts_install

    cpp_install
    python_install

    shell_install

    vscode_install
    ui_install

    virt_install

    config_install

    set_zsh_as_default
}

is_fedora || err_exit "This script works only on Fedora. Quitting."

bootstrap "Fedora desktop setup(desktop)"

}
