#! /usr/bin/env bash

{

source <(curl -s https://dub.sh/z3pTnAK)

main() {
    dotfiles_install
    essential_install

    cli_config

    has_cmd chsh || dnfi util-linux-user
    set_zsh_as_default
}

is_rh || err_exit "This script works only on Fedora/RockyLinux. Quitting."

bootstrap "Fedora/RockyLinux setup"

}
