#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    dotfiles_install
    essential_install

    go_install
    snap_install
    flathub_install
    brew_install
    rust_install
    pnpm_install

    shell_install

    cpp_install
    python_install

    neovim_install

    virt_install

    cli_config_install

    dnfi util-linux-user
    set_zsh_as_default
}

is_rh || err_exit "This installer works only on Rocky Linux. Quitting."

bootstrap "Rocky Linux development system"

}
