#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    essential_install
    dotfiles_install

    go_install
    rust_install
    pnpm_install

    shell_install

    cpp_install
    python_mini_install

    ct_install

    config_install


    set_zsh_as_default
}

is_rh || err_exit "This installer works only on Rocky Linux. Quitting."

bootstrap "Rocky Linux development system(vm)"

}
