#! /usr/bin/env bash

set -euo pipefail -o errtrace

main() {
  local remote-ip="$1"
  local hostname="$2"
  nix run github:nix-community/nixos-anywhere -- --flake .#"${hostname}" \
    --generate-hardware-config nixos-generate-config ./hardware-configuration.nix \
    --target-host "root@${remote-ip}"
}

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <remote-host-ip> <remote-hostname>"
  exit 1
fi

main "$@"
