#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

brewi() {
    for p in "$@"; do
        slog "Installing package $p"
        brew install "$p"
    done
}

atomic_brew_apps_install() {
    has_cmd wget || brew install wget
    has_cmd unzip || brew install unzip
    has_cmd trash || brew install trash-cli
    has_cmd zsh || brew install zsh
    has_cmd tmux || brew install tmux
    has_cmd xclip || brew install xclip
    has_cmd xsel || brew install xsel
    has_cmd urlview || brew install urlview
    has_cmd fzf || brew install fzf
    has_cmd fd || brew install fd
    has_cmd zoxide || brew install zoxide
    has_cmd hyperfine || brew install hyperfine
    has_cmd micro || brew install micro
}

atomic_shell_install() {
    webi_install
    atomic_brew_apps_install
    webi-shell_install
}

atomic_virt_install() {
    declare -a pkgs

    has_cmd virt-manager || pkgs+=("virt-manager" "libvirt")
    has_cmd distrobox || pkgs+=("distrobox")
    has_cmd cockpit || pkgs+=("cockpit" "cockpit-file-sharing" "cockpit-machines" "cockpit-pcp"
    "cockpit-podman" "cockpit-storaged")
    has_cmd pipx || pkgs+=("pipx")

    sudo rpm-ostree install -y "${pkgs[@]}"
}

main() {
    cmd_check git tar curl

    atomic_shell_install
    atomic-fedora-desktop-group_install
    atomic_virt_install
}

is_atomic_fedora || err_exit "This script works only on Kinoite/Silverblue. Quitting."

bootstrap "Fedora desktop setup(desktop)"
slog "Please reboot and run script ~/.config/dotfiles/installers/post-atomic"
}
