#! /usr/bin/env bash

{

command -v curl > /dev/null || {
    echo "curl not found. Please install curl and try again."
    exit 1
}

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    dotfiles_install
    fonts_install
    config_install
}

slog "This script doesn't install any packages. It only sets up dotfiles."

bootstrap "config setup"

slog "Also make sure to set nerd font in your terminal emulator."

}
