#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    sudo rpm-ostree install zsh tmux trash-cli virt-manager libvirt
    sudo systemctl enable --now libvirtd

    kinoite-desktop-group_install
}

is_atomic_fedora || err_exit "This script works only on Kinoite. Quitting."

bootstrap "Fedora desktop setup(desktop)"

}
