#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    kinoite-desktop-group_install

}

is_kinoite || err_exit "This script works only on Kinoite. Quitting."

bootstrap "Fedora desktop setup(desktop)"

}
