#! /usr/bin/env bash

{

macos_settings_install() {
    defaults write -g NSWindowShouldDragOnGesture -bool true
}

macos_config_install() {
    stow -d $DOT_DIR/stow -t $HOME --dotfiles -R aerospace
    stow -d $DOT_DIR/stow -t $HOME --dotfiles -R amethyst
}

ui_install() {
    bi deluge
    bi visual-studio-code
    bic telegram
    bic zoom
    bic ghostty
    bic google-chrome
    bic microsoft-remote-desktop
    bic nikitabobko/tap/aerospace
}

bic() {
    for cmd in "$@"; do
        brew install -q --cask "$cmd"
    done
}

core_install() {
    slog "Install xcode"
    xcode-select --install
    brew_install

    bi coreutils bash
    bis curl wget trash tree unzip coreutils gum stow
}

essential_install() {
    slog "Installing Essential packages"

    core_install
    webi_install
    mise_install

    bis gawk p7zip cmake unar zip

    slog "Essential packages installation done!"
}

cli_install() {
    bis tmux pkg-config urlview
    bi zsh-syntax-highlighting zsh-autosuggestions
    bi golang rust ripgrep neovim neovide luarocks lazydocker
    bi starship gping broot mcfly jq
    bi install reattach-to-user-namespace

    gh extension install github/gh-copilot
}

fonts_install() {
    bic font-jetbrains-mono-nerd-font font-monaspace-nerd-font font-caskaydia-mono-nerd-font
}

cpp_install() {
    slog "Installing C++"

    bi cmake boost catch2 ccache cppcheck pre-commit

    slog "C++ installation done!"
}

virt_install() {
    slog "Installing virtualization packages"

    softwareupdate --install-rosetta --agree-to-license
    bi podman
    bic podman-desktop
    bi colima
    # podman machine set --rootful
    # sudo /opt/homebrew/Cellar/podman/4.9.2/bin/podman-mac-helper install

    dir_exists /Applications/Docker.app || bic docker

    slog "Virtualization packages installation done!"
}

python_uv_install() {
    curl -LsSf https://astral.sh/uv/install.sh | sh
}

pyenv_mac_install() {
    slog "Installing pyenv"
    bi pyenv
    bi pyenv-virtualenv
}

}
