#! /usr/bin/env bash

{

sudo systemctl enable --now cockpit.socket
sudo systemctl enable --now firewalld
sudo firewall-cmd --add-service=cockpit
sudo firewall-cmd --add-service=cockpit --permanent

sudo systemctl enable --now libvirtd

}
