#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    brew install trash-cli
    dotfiles_install
    webi_install
    webi pathman

    webi curlie lsd shfmt gh lazygit gtop tldr
    gh extension install github/gh-copilot
    brew install neovim neovide shellcheck gdu 
    brew install git-delta procs fzf ripgrep fd hyperfine bat zoxide
    brew install cheat curlie lazygit duf choose-rust sd bottom xh

    fonts_install

    flatpak_apps_install

    config_install
}

is_atomic_fedora || err_exit "This script works only on atomic fedora desktops(silverblue, kinoite etc). Quitting."

bootstrap "Fedora Atomic desktop setup(desktop)"

}
