export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export DOT_DIR=${DOT_DIR:-$HOME/.ilm}

[[ -d $DOT_DIR ]] || return

source $DOT_DIR/share/shellrc

# if interactive shell then return
[[ $- == *i* ]] || return

has_cmd mise && eval "$(mise activate bash)"
has_cmd pixi && eval "$(pixi completion --shell bash)"

source_if_exists $DOT_DIR/share/fns
source_if_exists $DOT_DIR/share/aliases

source_if_exists "$HOME/.localbashrc"
source_if_exists "$XDG_CONFIG_HOME/localbashrc"

if ! is_ublue && has_cmd starship; then
    has_cmd direnv && eval "$(direnv hook bash)"
    has_cmd zoxide && eval "$(zoxide init bash)"
    has_cmd fzf && source <(fzf --bash)
    has_cmd atuin && eval "$(atuin init bash --disable-up-arrow --disable-ctrl-r)"
    eval "$(starship init bash)"
fi

# one_shell_tmux
