#! /usr/bin/env sh


has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

spath_export() {
  if [ -d "$1" ]; then
    export PATH="$1:$PATH"
  fi
}

source_if_exists() {
  if [ -f "$1" ]; then
    # shellcheck disable=SC1090
    . "$1"
  fi
}

has_cmd nvim && export MANPAGER="nvim +Man!"

export LANG=en_US.UTF-8

export HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=1

export ELECTRON_OZONE_PLATFORM_HINT=wayland

export LIBVIRT_DEFAULT_URI=qemu:///system

# source_if_exists "$HOME/.config/envman/load.sh"

source_if_exists "$HOME/.cargo/env"

source_if_exists /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

has_cmd webi && source_if_exists "$XDG_CONFIG_HOME/envman/PATH.env"

export DOTNET_ROOT="$HOME/.dotnet"
export GOPATH="$HOME/go"
export VOLTA_HOME="$HOME/.volta"

spath_export "/usr/bin"
spath_export "/snap/bin"
spath_export "$GOPATH/bin"
spath_export "$XDG_CONFIG_HOME/emacs/bin"
spath_export "$HOME/.local/bin"
spath_export "$HOME/bin"
spath_export "$HOME/.bin"
spath_export "$DOT_DIR/bin"
spath_export "$DOT_DIR/bin/vt"
spath_export "$HOME/Applications"
spath_export "$HOME/AppImages"
spath_export "$HOME/.local/share/pypoetry"
spath_export "$XDG_CONFIG_HOME/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin"
spath_export "$HOME/.console-ninja/.bin"
spath_export "$HOME/.pixi/bin"
spath_export "${VOLTA_HOME}/bin"

if [ -z "$XDG_DATA_HOME" ]; then
  export XDG_DATA_HOME="$HOME/.local/share"
fi

if [ -z "$XDG_CACHE_HOME" ]; then
  export XDG_CACHE_HOME="$HOME/.cache"
fi

# has_cmd firefox && export BROWSER=firefox
# has_cmd alacritty && export TERM=alacritty
# has_cmd qt5ct && export QT_QPA_PLATFORMTHEME=qt5ct

if has_cmd "$HOME/bin/docker"; then
  DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
  export DOCKER_HOST
fi

# export TERM=xterm-256color

# export FZF_DEFAULT_OPTS=" \
#     --color=bg+:#313244,bg:#1E1E2E,spinner:#F5E0DC,hl:#F38BA8 \
#     --color=fg:#CDD6F4,header:#F38BA8,info:#CBA6F7,pointer:#F5E0DC \
#     --color=marker:#B4BEFE,fg+:#CDD6F4,prompt:#CBA6F7,hl+:#F38BA8 \
#     --color=selected-bg:#45475A \
#     --color=border:#6C7086,label:#CDD6F4"

