window:
  opacity: 0.9
padding:
  x: 10
y: 10
decorations: "Full"
decorations_theme_variant: "Light" # "Dark"

font:
  normal:
    family: "MonaspiceRn Nerd Font Mono"
bold:
  family: "MonaspiceRn Nerd Font Mono"
italic:
  family: "MonaspiceRn Nerd Font Mono"
bold_italic:
  family: "MonaspiceRn Nerd Font Mono"
size: 15.0
