#! /usr/bin/env bash

{

sudo apt-get install -y curl sudo
source <(curl -s https://dub.sh/z3pTnAK)

main() {
    dotfiles_install
    essential_install

    go_install
    rust_install
    pnpm_install

    shell_install

    neovim_install

    cli_config

    set_zsh_as_default
}

is_apt || err_exit "This installer works only on Debian/Ubuntu. Quitting."

bootstrap "Debian development system"

}
