#! /usr/bin/env bash

{

if command -v apt-get > /dev/null; then
    sudo apt-get install -y curl sudo
else
    echo "apt-get not found. Please install apt-get and try again."
    exit 1
fi

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    dotfiles_install
    essential_install

    go_install
    rust_install
    pnpm_install
    python_install
    cpp_install

    neovim_install

    ct_install

    config_install

    set_zsh_as_default
}

is_debian || err_exit "This installer works only on Debian. Quitting."

bootstrap "Debian development system(vm)"

}
