#! /usr/bin/env bash

{

sudo apt-get install -y curl sudo
source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    dotfiles_install
    essential_install

    go_install
    rust_install
    pnpm_install
    python_install
    cpp_install

    neovim_install

    virt_install

    cli_config

    set_zsh_as_default
}

is_debian || err_exit "This installer works only on Debian. Quitting."

bootstrap "Debian development system"

}
