#! /usr/bin/env bash

{

sudo apt-get install -y curl sudo
source <(curl -s https://raw.githubusercontent.com/pervezfunctor/dotfiles/master/scripts/utils)

main() {
    dotfiles_install
    essential_install

    cli_config

    set_zsh_as_default
}

is_apt || err_exit "This installer works only on Ubuntu or Debian. Quitting."

export DEBIAN_FRONTEND=noninteractive

bootstrap "Ubuntu/Debian setup"

}
