#! /usr/bin/env bash

{

nano-group_install() {
    core_install
    dotfiles_install

    config_install
    set_zsh_as_default
}

min-group_install() {
    essential_install
    dotfiles_install

    config_install
    set_zsh_as_default
}

shell-group_install() {
    essential_install
    dotfiles_install

    go_install
    rust_install
    pnpm_install

    shell_install
    neovim_install

    config_install
    set_zsh_as_default
}

vm-group_install() {
    essential_install
    dotfiles_install

    go_install
    rust_install
    pnpm_install

    python_install
    cpp_install

    shell_install
    neovim_install

    ct_install

    config_install
    set_zsh_as_default
}

desktop-group_install() {
    essential_install
    dotfiles_install

    flathub_install
    snap_install
    brew_install

    go_install
    rust_install
    pnpm_install

    fonts_install

    cpp_install
    python_install

    shell_install

    neovim_install
    vscode_install
    apps_install

    virt_install

    config_install
    set_zsh_as_default
}

desktop-apps-group_install() {
    core_install
    dotfiles_install

    flathub_install
    snap_install

    fonts_install

    vscode_install
    apps_install

    virt_install

    config_install
    set_zsh_as_default
}

all-group_install() {
    desktop-group_install
    asdf_install
    emacs_install
}

clould-group_install() {
    essential_install
    dotfiles_install

    cpp_install
    python_install

    config_install
    set_zsh_as_default
}

atomic-fedora-desktop-group_install() {
    flathub_install

    fonts_install

    flatpak_apps_install
    fpi org.chromium.Chromium
    fpi com.visualstudio.code
    fpi io.neovim.nvim
    fpi org.gnu.emacs
    fpi org.virt_manager.virt-viewer

    config_install
}

}
