#! /usr/bin/env bash

{

nano-group_install() {
    core_install
    dotfiles_install

    config_install
    set_zsh_as_default
}

min-group_install() {
    essential_install
    dotfiles_install

    config_install
    set_zsh_as_default
}

shell-group_install() {
    essential_install
    dotfiles_install

    go_install
    rust_install
    pnpm_install

    shell_install

    config_install
    set_zsh_as_default
}

vm-group_install() {
    essential_install
    dotfiles_install

    go_install
    rust_install
    pnpm_install

    python_mini_install
    cpp_install

    shell_install

    ct_install

    config_install
    set_zsh_as_default
}

desktop-group_install() {
    essential_install
    dotfiles_install

    go_install
    rust_install
    pnpm_install

    fonts_install

    cpp_install
    python_install

    shell_install

    vscode_install
    ui_install

    virt_install

    config_install
    set_zsh_as_default
}

desktop-apps-group_install() {
    core_install
    dotfiles_install

    flathub_install
    snap_install

    fonts_install

    vscode_install
    ui_install

    virt_install

    config_install
    set_zsh_as_default
}

all-group_install() {
    desktop-group_install
    asdf_install
    emacs_install
}

clould-group_install() {
    essential_install
    dotfiles_install

    cpp_install
    python_mini_install

    config_install
    set_zsh_as_default
}

atomic_fedora_install() {
    fonts_install
    flathub_install

    if has_cmd distrobox; then
        cnt_cmd="distrobox"
    elif has_cmd toolbox; then
        cnt_cmd="toolbox"
    else
        err_exit "You need either distrobox or toolbox installed"
    fi

    fpi org.chromium.Chromium
    fpi com.visualstudio.code
    fpi io.neovim.nvim


    if [ $cnt_cmd == "toolbox" ]; then
        has_cmd chromium || alias chromium="flatpak run org.chromium.Chromium"
        has_cmd nvim || alias nvim="flatpak run io.neovim.nvim"
        has_cmd code || alias code="flatpak run com.visualstudio.code"
    fi

    flatpak_apps_install

    slog "Entering default distrobox container"
    $cnt_cmd enter

    essential_install
    dotfiles_install
    webi_install

    cli_install
    config_install

    if [ $cnd_cmd == "distrobox" ]; then
        si chromium xsel xclip wl-clipboard gnome-keyring
        vscode_install
    fi

    set_zsh_as_default

    $cnt_cmd exit
    slog "Exiting default distrobox container"

    atomic_virt_install
}

# atomic-fedora-desktop-group_install() {
#     atomic_pkgs_install
#     webi_install

#     dotfiles_install
#     flathub_install

#     atomic_shell_install
#     webi-shell_install

#     fonts_install

#     flatpak_apps_install

#     fpi org.chromium.Chromium
#     fpi com.visualstudio.code
#     fpi io.neovim.nvim

#     has_cmd chrome || alias chrome="flatpak run org.chromium.Chromium"
#     has_cmd code || alias code="flatpak run com.visualstudio.code"
#     has_cmd nvim || alias nvim="flatpak run io.neovim.nvim"

#     config_install

#     atomic_virt_install

#     set_zsh_as_default
# }

# atomic-fedora-vm-desktop-group_install() {
#     atomic_pkgs_install
#     webi_install

#     dotfiles_install
#     flathub_install

#     atomic_shell_install
#     webi-shell_install

#     fonts_install

#     fpi org.chromium.Chromium
#     fpi com.visualstudio.code
#     fpi io.neovim.nvim

#     has_cmd chromium || alias chromium="flatpak run org.chromium.Chromium"
#     has_cmd code || alias code="flatpak run com.visualstudio.code"
#     has_cmd nvim || alias nvim="flatpak run io.neovim.nvim"

#     config_install

#     set_zsh_as_default
# }

}
