#! /usr/bin/env bash

{

fpi() {
    for pkg in "$@"; do
        flatpak install -y --user flathub "$pkg"
    done
}

flatpak_apps_install() {
    if ! has_cmd flatpak; then
        slog "flatpak not installed, skipping flatpak apps"
        return 1
    fi

    fpi org.telegram.desktop
    # fpi com.jetbrains.CLion
    # fpi com.google.Chrome
    fpi org.deluge_torrent.deluge
    fpi us.zoom.Zoom
    fpi org.wezfurlong.wezterm
    fpi io.github.shiftey.Desktop
}

astro_install() {
    slog "Installing AstroNvim"

    fmv ~/.config/nvim ~/.config/nvim.bak
    fmv ~/.local/share/nvim ~/.local/share/nvim.bak
    fmv ~/.local/state/nvim ~/.local/state/nvim.bak
    fmv ~/.cache/nvim ~/.cache/nvim.bak

    sclone --depth=1 https://github.com/AstroNvim/template ~/.config/nvim
    frm ~/.config/nvim/.git

    sclone https://github.com/pervezfunctor/astro-config.git ~/.config/nvim/lua/user

     [[ "$USER" == "pervez" ]] || frm ~/.config/nvim/lua/user/.git
    slog "Please configure AstroNvim by editing files in ~/.config/nvim/lua/user"

    slog "AstroNvim installation done!"
}

zsh_config_install() {
    slog "Installing zsh"

    smd ~/.zsh
    sclone --depth=1 https://github.com/sindresorhus/pure.git ~/.zsh/pure
    sclone --depth=1 https://github.com/djui/alias-tips.git ~/.zsh/alias-tips

    fln "${DOT_DIR}/configs/zshrc" ~/.zshrc

    slog "zsh installation done!"
}

tmux_config_install() {
    slog "tmux config"

    smd ~/.config/tmux
    fln "${DOT_DIR}/configs/tmux.conf" ~/.config/tmux/tmux.conf
}

treesitter_install() {
    has_cmd tree-sitter && return 0

    if has_cmd cargo; then
      cargo install tree-sitter-cli
    elif has_cmd pnpm; then
      pnpm install -g tree-sitter-cli
    elif has_cmd npm; then
      npm install -g tree-sitter-cli
    else
      slog "tree-sitter-cli not installed"
    fi
}

neovim_install() {
    has_cmd nvim && return 0

    slog "Installing neovim..."

    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x nvim.appimage

    ./nvim.appimage --appimage-extract

    sudo mv squashfs-root /
    sudo ln -s /squashfs-root/AppRun /usr/bin/nvim
    frm nvim.appimage

    treesitter_install

    si luarocks

    if has_cmd npm; then
        npm install -g neovim
    elif has_cmd npm; then
        npm install -g neovim
    fi

    has_cmd pip && pip install --user neovim

    slog "Neovim installation done!"
}

micro_install() {
    has_cmd micro && return 0

    slog "Installing micro"

    curl https://getmic.ro | bash
    sudo mv micro /usr/bin/

    slog "micro installation done!"
}

rust_install() {
    file_exists "$HOME/.cargo/env" && source "$HOME/.cargo/env"

    has_cmd rustup && return 0

    slog "Installing rust"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "$HOME/.cargo/env"

    slog "rust installation done!"
}

miniconda_install() {
    has_cmd conda && return 0
    dir_exists ~/miniconda3 && return 0

    slog "Installing miniconda"

    smd ~/miniconda3
    download_to https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
    bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
    frm ~/miniconda3/miniconda.sh
    has_cmd bash && ~/miniconda3/bin/conda init bash
    has_cmd zsh && ~/miniconda3/bin/conda init zsh

    slog "miniconda installation done!"
}

pnpm_install() {
    has_cmd pnpm && return 0

    slog "Installing pnpm"
    curl -sSL https://get.pnpm.io/install.sh | sh -

    slog "Installing node"
    pnpm env use --global latest

    has_cmd bash && pnpm install-completion bash
    has_cmd zsh && pnpm install-completion zsh
}

web_install() {
    slog "Installing npm packages globally"
    pnpm install -g ndb @antfu/ni
    pnpm install -g tsx vite-node zx turbo

    if ! grep "fs.inotify.max_user_watches" /etc/sysctl.conf > /dev/null; then
        echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf > /dev/null && sudo sysctl -p
    fi

    if is_apt; then
        pnpm dlx playwright install-deps
        pnpm dlx playwright install
    fi
}

brew_install() {
    has_cmd brew && return 0

    slog "Installing homebrew"
    NONINTERACTIVE=1 /bin/bash -c "$(curl -sSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    slog "homebrew installation done!"
}

monaspace_install() {
    file_exists ~/.local/share/fonts/MonaspaceRadon-Regular.otf && return 0

    smd ~/.local/share/fonts

    frm /tmp/monaspace /tmp/monaspace.zip
    wget https://github.com/githubnext/monaspace/releases/download/v1.000/monaspace-v1.000.zip -O /tmp/monaspace.zip
    unzip -d /tmp/monaspace -o /tmp/monaspace.zip


    cp /tmp/monaspace/monaspace-*/fonts/otf/* ~/.local/share/fonts
    cp /tmp/monaspace/monaspace-*/fonts/variable/* ~/.local/share/fonts

    frm /tmp/monaspace /tmp/monaspace.zip
}

nerd_font_install() {
    smd ~/.local/share/fonts

    if ! file_exists ~/.local/share/fonts/MonaspiceRnNerdFont-Regular.otf; then
        frm /tmp/monaspace /tmp/CascadiaMono.zip
        wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/CascadiaMono.zip -O /tmp/CascadiaMono.zip
        unzip -d /tmp/monaspace -o /tmp/CascadiaMono.zip
        cp /tmp/monaspace/*.ttf ~/.local/share/fonts
        frm /tmp/monaspace /tmp/CascadiaMono.zip
    fi

    if ! file_exists ~/.local/share/fonts/MonaspiceRnNerdFont-Regular.otf; then
        frm /tmp/monaspace /tmp/Monaspace.zip
        wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Monaspace.zip -O /tmp/Monaspace.zip
        unzip -d /tmp/monaspace -o /tmp/Monaspace.zip
        cp /tmp/monaspace/*.otf ~/.local/share/fonts
        frm /tmp/monaspace /tmp/Monaspace.zip
    fi
}

fonts_install() {
    if ! has_cmd wget || ! has_cmd unzip; then
        warn "wget and unzip not installed, skipping fonts"
        return 1
    fi

    slog "Installing fonts"

    monaspace_install
    nerd_font_install

    if is_apt; then
        si fonts-cascadia-code fonts-jetbrains-mono
    elif is_rh; then
        is_atomic_fedora || si cascadia-fonts-all jetbrains-mono-fonts-all
    fi

    slog "Fonts installation done!"
}

doom_install() {
    dir_exists ~/.config/doom && return 0

    sclone --depth=1 https://github.com/doomemacs/doomemacs ~/.config/emacs
    fmv ~/.config/doom ~/.config/doom.backup
    sclone https://github.com/pervezfunctor/doomemacs-config ~/.config/doom

    slog "Configure doom"
    doom sync
    doom env

    has_cmd update-locale && sudo update-locale LANG=en_US.UTF8
}

emacs_install() {
    slog "Installing emacs"

    if is_apt; then
      si -y --no-install-recommends emacs
    elif is_rh; then
        si emacs
    elif is_mac; then
        brew tap railwaycat/emacsmacport
        brew install emacs-mac --with-modules
        ln -s /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app
    fi

    slog "emacs installation done!"
}

git_conf() {
    git config --global "$@"
}

git_config_install() {
    is_wsl && git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"

    git_conf init.defaultBranch main
    git_conf pull.ff only
    git_conf delta.navigate true
    git_conf delta.line-numbers true
    git_conf delta.syntax-theme "Monokai Extended"
    git_conf delta.side-by-side true
    git_conf merge.conflictStyle diff3
    git_conf interactive.diffFilter "delta --color-only"
    git_conf fetch.prune true

    if [[ "$USER" == "pervez" ]]; then
        git_conf user.name "Pervez Iqbal"
        git_conf user.email "pervefunctor@gmail.com"
    fi
}

go_install() {
    if ! has_cmd go; then
        slog "Installing go"

        sudo rm -rf /usr/local/go
        VERSION=$(curl -sSL "https://go.dev/VERSION?m=text" | head -n 1)
        frm /tmp/${VERSION}.linux-amd64.tar.gz
        wget "https://dl.google.com/go/${VERSION}.linux-amd64.tar.gz" -O /tmp/"${VERSION}.linux-amd64.tar.gz"
        slog "Untar ${VERSION}.linux-amd64.tar.gz"
        sudo tar -C /usr/local -xzf /tmp/"${VERSION}.linux-amd64.tar.gz"
        frm /tmp/${VERSION}.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin

        slog "go installation done!"
    fi

    slog "Installing go dev tools..."

    go install golang.org/x/lint/golint@latest
    go install golang.org/x/tools/cmd/goimports@latest
    go install golang.org/x/tools/gopls@latest
    go install github.com/go-delve/delve/cmd/dlv@latest
    go install github.com/ramya-rao-a/go-outline@latest
    go install github.com/acroca/go-symbols@latest
    go install github.com/mdempsky/gocode@latest
    go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
    go install github.com/cweill/gotests/gotests@latest
    go install github.com/fatih/gomodifytags@latest
    go install github.com/josharian/impl@latest
    go install github.com/haya14busa/goplay/cmd/goplay@latest
    go install github.com/go-delve/delve/cmd/dlv@latest
    go install github.com/davidrjenni/reftools/cmd/fillstruct@latest
    go install github.com/godoctor/godoctor@latest
    go install github.com/zmb3/gogetdoc@latest
    go install github.com/jstemmer/gotags@latest
    go install github.com/fatih/motion@latest
    go install github.com/klauspost/asmfmt/cmd/asmfmt@latest
    go install github.com/kisielk/errcheck@latest
    go install mvdan.cc/gofumpt@latest
    go install github.com/fatih/gomodifytags@latest

    slog "go dev tools installation done!"
}

docker_common_install() {
    sudo groupadd docker
    sudo usermod -aG docker ${USER}

    sudo systemctl --now enable docker
    sudo systemctl --now enable containerd
}

docker_install() {
    has_cmd docker && return 0

    slog "Installing docker..."

    frm /tmp/get-docker.sh
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sudo sh /tmp/get-docker.sh
    frm /tmp/get-docker.sh


    docker_common_install

    slog "Docker installation done!"
}

code_server_install() {
    has_cmd code-server && return 1

    slog "Installing code-server"
    curl -sSL https://code-server.dev/install.sh | sh
    slog "code-server installation done!"

    # slog "Installing coder"
    # curl -L https://coder.com/install.sh | sh
    # slog "coder installation done!"
}

conan_install() {
    has_cmd conan && return 1

    python3 -m pip install --user conan
}

cmake_install() {
    has_cmd /usr/local/bin/cmake && return 1

    CMAKE_VERSION="3.28.3"
    ARCH=$(uname -m)
    CMAKE_BINARY_NAME="cmake-${CMAKE_VERSION}-linux-${ARCH}.sh"
    CMAKE_CHECKSUM_NAME="cmake-${CMAKE_VERSION}-SHA-256.txt"

    TMP_DIR=$(mktemp -d -t cmake-XXXXXXXXXX)
    cd "${TMP_DIR}"
    curl -sSL "https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${CMAKE_BINARY_NAME}" -O
    curl -sSL "https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${CMAKE_CHECKSUM_NAME}" -O

    sha256sum -c --ignore-missing "${CMAKE_CHECKSUM_NAME}"
    sudo mkdir /opt/cmake
    sudo sh "${TMP_DIR}/${CMAKE_BINARY_NAME}" --prefix=/opt/cmake --skip-license

    sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
    sudo ln -s /opt/cmake/bin/ctest /usr/local/bin/ctest
    frm "${TMP_DIR}"
}

go_shell_install() {
    if ! has_cmd go; then
        warn "go not installed, skipping some shell tools"
        return 1
    fi
    has_cmd cheat || go install github.com/cheat/cheat/cmd/cheat@latest
    has_cmd curlie || go install github.com/rs/curlie@latest
    has_cmd lazygit || go install github.com/jesseduffield/lazygit@latest
    has_cmd gdu || go install github.com/dundee/gdu/v5/cmd/gdu@latest
    has_cmd lemonade || go install github.com/lemonade-command/lemonade@latest
    has_cmd duf || go install github.com/muesli/duf@latest
}

rust_shell_install() {
    if ! has_cmd cargo; then
        warn "cargo not installed, skipping some shell tools"
        return 1
    fi

    rustup update stable

    cargoi starship
    has_cmd delta || cargoi git-delta
    has_cmd dust || cargoi du-dust
    has_cmd choose || cargoi choose
    has_cmd sd || cargoi sd
    has_cmd procs || cargoi procs
    has_cmd btm || cargoi bottom
    has_cmd xh || cargoi xh
    has_cmd lsd || cargoi lsd
}

pnpm_shell_install() {
    if ! has_cmd pnpm; then
        warn "pnpm not installed, skipping some shell tools"
    fi

    pnpm install -g degit tldr gtop
    pnpm install -g @githubnext/github-copilot-cli
}

shell_install() {
    go_shell_install
    rust_shell_install
    pnpm_shell_install
}

config_install() {
    has_cmd zsh && zsh_config_install
    has_cmd tmux && tmux_config_install
    has_cmd nvim && astro_install
    has_cmd emacs && doom_install
    has_cmd git && git_config_install

    if has_cmd alacritty; then
        smd ~/.config/alacritty
        scp "${DOT_DIR}/configs/alacritty.yml" ~/.config/alacritty/alacritty.yml
    fi
}

poetry_install() {
    has_cmd poetry && return 0

    if has_cmd python3; then
        curl -sSL https://install.python-poetry.org | python3 -
        smd ~/.zfunc
        poetry completions zsh > ~/.zfunc/_poetry
    else
        warn "python3 not installed, skipping poetry"
    fi
}

pyenv_install() {
    has_cmd pyenv && return 0

    sclone  https://github.com/yyuu/pyenv.git ~/.pyenv
    sclone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
}

anaconda_install() {
    if has_cmd pyenv; then
        if ! pyenv versions | grep anaconda > /dev/null; then
            slog "Installing anaconda"
            local anacondaversion=`pyenv install --list | grep anaconda | tail -1`
            pyenv install $anacondaversion
        fi
    else
        warn "pyenv not installed, skipping anaconda"
    fi
}

pyenv_miniconda_install() {
    if has_cmd pyenv; then
        if ! pyenv versions | grep miniconda > /dev/null; then
            slog "Installing miniconda"
            local minicondaversion=`pyenv install --list | grep miniconda | tail -1`
            pyenv install $minicondaversion
        fi
    else
        warn "pyenv not installed, skipping miniconda"
    fi
}

python_install() {
    pyenv_install

    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"

    anaconda_install
    poetry_install
}

asdf_install() {
    has_cmd asdf && return 1
    dir_exists ~/.asdf && return 1

    slog "Installing asdf"
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0
    slog "asdf installation done!"
}

}
