#! /usr/bin/env bash

{

si() {
    for p in "$@"; do
        slog "Installing package $p"
        sudo pacman -S --needed --quiet --noconfirm "$p"
    done
}

update_packages() {
    slog "Updating"

    if ! sudo pacman -Syu --noconfirm --quiet; then
        err_exit "pacman update/upgrade failed, quitting"
    fi
}

core_install() {
    update_packages

    si curl wget git base-devel trash-cli tree micro
    si tar unzip
}

sys_python_install() {
    si python python-pipx python-pip python-setuptools python-wheel python-virtualenv
    pipx install uv
}

yay_install() {
    frm /tmp/yay
    git clone https://aur.archlinux.org/yay.git /tmp/yay && cd /tmp/yay && makepkg -si && cd - && frm /tmp/yay
}

essential_install() {
    slog "Installing essential packages"

    core_install

    zsh zsh-completions base_devel unarchiver zip
    si gawk tmux pkg-config p7zip cmake
    si readline sqlite libffi zlib xz

    sys_python_install

    webi_install
    mise_install
    brew_install
    webi curlie

    si pkgfile
    si gum
    sudo pkgfile --update

    yay -Sy --noconfirm snapd

    slog "Essential packages installation done!"
}

cli_install() {
    si neovim github-cli shellcheck shfmt python-pynvim
    si sd lsd gdu bat hyperfine fd fzf ripgrep zoxide
    gh extension install github/gh-copilot
}

cpp_install() {
    slog "Installing C++"

    si gcc gdb boost boost-libs catch2 libc++ clang llvm
    si doxygen graphviz ccache cppcheck pre-commit
    si valgrind ltrace strace lldb lld

    cmake_install
    conan_install

    slog "C++ installation done!"
}

vscode_install() {
    yay -Sy --noconfirm visual-studio-code-bin
}

ui_install() {
    vscode_install
    si chromium virt-manager neovide gnome-keyring xsel xclip wl-clipboard ghostty
    flathub_install
    flatpak_apps_install
}

cockpit_install() {
    has_cmd cockpit && return 1

    slog "Installing cockpit"

    si cockpit cockpit-machines cockpit-packagekit cockpit-pcp cockpit-podman cockpit-storaged
    sudo systemctl enable --now cockpit.socket

    slog "cockpit installation done!"
}

podman_install() {
    si podman podman-compose
}

libvirt_install() {
    si buildah libvirt virt-install distrobox

    sudo systemctl enable --now libvirtd
}

docker_install() {
    si docker docker-compose
    docker_common_install
}

incus_install() {
    si incus
    incus_config_install
}

ct_install() {
    si incus
    docker_install
    podman_install
    si buildah distrobox
    cockpit_install
}

incus_install() {
    si incus
}

virt_install() {
    ct_install
    libvirt_install
    code_server_install
}

}
