#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)


main() {
    dotfiles_install
    essential_install

    go_install
    rust_install
    pnpm_install

    fonts_install

    cpp_install
    python_install

    shell_install

    ui_install

    virt_install

    config_install

    set_zsh_as_default
}

is_arch || err_exit "This script works only on Fedora. Quitting."

bootstrap "Arch desktop setup(desktop)"

}
