#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    essential_install
    dotfiles_install

    config_install

    set_zsh_as_default
}

is_arch || err_exit "This script works only on Arch. Quitting."

bootstrap "Arch setup(min)"

}
