#!/usr/bin/env bash

# Exit on errors
set -euo pipefail

PROXMOX_STORAGE="local-lvm"
VM_ID=9200
VM_NAME="fedora-template"
FEDORA_IMAGE_URL="https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-41-1.4.x86_64.qcow2"
DISK_SIZE="32G"
MEMORY="8192"
CORES="4"
USERNAME="pervez"
PASSWORD="program"

usage() {
    echo "Usage: $0 -i VM_ID -n VM_NAME -s STORAGE -u FEDORA_IMAGE_URL [--disk-size DISK_SIZE] [--memory MEMORY] [--cores CORES] [--username USERNAME] [--password PASSWORD]"
    echo
    echo "Options:"

    echo "  -s, --storage STORAGE          Proxmox storage target (e.g., local-lvm)"
    echo "  -i, --vm-id VM_ID              Unique ID for the new VM"
    echo "  -n, --vm-name VM_NAME          Name for the VM"
    echo "  -d, --disk-size DISK_SIZE      Size of the VM disk (default: 20G)"
    echo "  -m, --memory MEMORY            VM memory in MB (default: 2048)"
    echo "  -c, --cores CORES              Number of CPU cores (default: 4)"
    echo "  -u, --username USERNAME        Username for cloud-init (default: pervez)"
    echo "  -p, --password PASSWORD        Password for cloud-init (default: program)"
    echo "  -U, --url FEDORA_IMAGE_URL     URL of the Fedora cloud image"
    echo "  -h, --help                     Display this help message"
    exit 1
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
    -s | --storage)
        PROXMOX_STORAGE="$2"
        shift
        ;;
    -i | --vm-id)
        VM_ID="$2"
        shift
        ;;
    -n | --vm-name)
        VM_NAME="$2"
        shift
        ;;
    -d | --disk-size)
        DISK_SIZE="$2"
        shift
        ;;
    -m | --memory)
        MEMORY="$2"
        shift
        ;;
    -c | --cores)
        CORES="$2"
        shift
        ;;
    -u | --username)
        USERNAME="$2"
        shift
        ;;
    -p | --password)
        PASSWORD="$2"
        shift
        ;;
    -U | --url)
        FEDORA_IMAGE_URL="$2"
        shift
        ;;
    -h | --help) usage ;;
    *)
        echo "Unknown parameter: $1"
        usage
        ;;
    esac
    shift
done

# Read options from options file, from the same directory as the script
CUR_DIR=$(dirname "$0")
if [ -f "$CUR_DIR/options" ]; then
    # shellcheck disable=SC1091
    source "$CUR_DIR/options"
fi

echo "Downloading Fedora image..."

if ! [ -f /tmp/fedora-cloud.qcow2 ]; then
    wget -O /tmp/fedora-cloud.qcow2 "$FEDORA_IMAGE_URL"
fi

# Create a new VM
echo "Creating VM $VM_NAME with ID $VM_ID..."
if ! qm create "$VM_ID" --name "$VM_NAME" \
    --memory "$MEMORY" \
    --cores "$CORES" \
    --ostype l26 \
    --agent 1 \
    --cpu host \
    --net0 virtio,bridge=vmbr0; then
    echo "Failed to create VM $VM_NAME with ID $VM_ID"
    exit 1
fi

echo "Importing disk to Proxmox storage..."
if ! qm importdisk "$VM_ID" /tmp/fedora-cloud.qcow2 "$PROXMOX_STORAGE"; then
    echo "Failed to import disk to Proxmox storage"
    exit 1
fi

echo "Attaching disk to VM..."
if
    ! qm set "$VM_ID" --scsihw virtio-scsi-pci \
        --scsi0 "$PROXMOX_STORAGE":"vm-$VM_ID"-disk-0,discard=on,ssd=1
then
    echo "Failed to attach disk to VM"
    exit 1
fi

echo "Resizing disk to $DISK_SIZE..."
if ! qm resize "$VM_ID" scsi0 "$DISK_SIZE"; then
    echo "Failed to resize disk to $DISK_SIZE"
    exit 1
fi

echo "Configuring boot options..."
if ! qm set "$VM_ID" --boot c --bootdisk scsi0; then
    echo "Failed to configure boot options"
    exit 1
fi

echo "Adding cloud-init drive..."
if ! qm set "$VM_ID" --ide2 "$PROXMOX_STORAGE:cloudinit"; then
    echo "Failed to add cloud-init drive"
    exit 1
fi

echo "Configuring cloud-init..."
if ! qm set "$VM_ID" --serial0 socket \
    --vga serial0 \
    --ipconfig0 ip=dhcp \
    --cipassword "$PASSWORD" \
    --ciuser "$USERNAME"; then
    echo "Failed to configure cloud-init"
    exit 1
fi

echo "Converting VM to template..."
if ! qm template "$VM_ID"; then
    echo "Failed to convert VM to template"
    exit 1
fi

# Clean up temporary files
# echo "Cleaning up..."
# rm -f /tmp/fedora-cloud.qcow2

echo "Fedora template $VM_NAME created successfully."
