#!/usr/bin/env bash

DOT_DIR=${DOT_DIR:-$HOME/.ilm}

# shellcheck disable=SC1091
source "$(dirname "$0")/utils"

set -eopipefail

# https://community-scripts.github.io/ProxmoxVE/scripts?id=post-pve-install
proxmox_init_install() {
    bash -c "$(wget -qLO - https://github.com/community-scripts/ProxmoxVE/raw/main/misc/post-pve-install.sh)"
}

proxmox_download_templates() {
    ubuntu_latest_tmpl=$(pveam available | awk '{print $2}' | grep "^ubuntu" | sort -r | head -n 1)
    pveam download local "$ubuntu_latest_tmpl"

    debian_latest_tmpl=$(pveam available | awk '{print $2}' | grep "^debian.*standard" | sort -r | head -n 1)
    pveam download local "$debian_latest_tmpl"

    rocky_latest_tmpl=$(pveam available | awk '{print $2}' | grep "^rockylinux.*default" | sort -r | head -n 1)
    pveam download local "$rocky_latest_tmpl"

    fedora_latest_tmpl=$(pveam available | awk '{print $2}' | grep "^fedora.*default" | sort -r | head -n 1)
    pveam download local "$fedora_latest_tmpl"

    arch_latest_tmpl=$(pveam available | awk '{print $2}' | grep "archlinux-base" | sort -r | head -n 1)
    pveam download local "$arch_latest_tmpl"

    centos_latest_tmpl=$(pveam available | awk '{print $2}' | grep "^centos.*default" | sort -r | head -n 1)
    pveam download local "$centos_latest_tmpl"

    opensuse_latest_tmpl=$(pveam available | awk '{print $2}' | grep "^opensuse.*default" | sort -r | head -n 1)
    pveam download local "$opensuse_latest_tmpl"
}

proxmox_lxc_create_all_templates() {
    local templates
    templates=$(ls /var/lib/vz/template/cache/)
    for tmpl in $templates; do
        echo "Creating LXC from template: $tmpl"
        lxc_create "$tmpl"
    done
}

proxmox_cloud_init_vms_install() {
    pushd "$DOT_DIR/extras/proxmox"
    ./debian-vm-template.sh
    qm clone 9100 101 --name debian-vm

    ./ubuntu-vm-template.sh
    qm clone 9400 104 --name ubuntu-vm

    ./rocky-vm-template.sh
    qm clone 9300 103 --name rocky-vm

    ./fedora-vm-template.sh
    qm clone 9200 102 --name fedora-vm
    popd
}

proxmox_packages_install() {
    apt-get -qq -y --no-install-recommends install git-core micro zsh-theme-powerlevel9k zsh
    # echo 'source /usr/share/powerlevel9k/powerlevel9k.zsh-theme' >>~/.zshrc
    # chsh -s /bin/zsh "$USER"
    # zsh_config_install
}

main() {
    proxmox_packages_install
    dotfiles_install
    bash_config_install
    zsh_min_config_install

    read -rp "Do you want to run proxmox setup script? (y/n): " answer
    if [[ "$answer" =~ ^[Yy]$ ]]; then
        proxmox_init_install
    fi

    read -rp "Do you want to download templates? (y/n): " answer
    if [[ "$answer" =~ ^[Yy]$ ]]; then
        pveam update
        proxmox_download_templates
    fi

    read -rp "Do you want to install cloud-init vms? (y/n): " answer
    if [[ "$answer" =~ ^[Yy]$ ]]; then
        proxmox_cloud_init_vms_install
    fi

    read -rp "Do you want to create LXC from all templates? (y/n): " answer
    if [[ "$answer" =~ ^[Yy]$ ]]; then
        proxmox_lxc_create_all_templates
    fi
}

main
