#! /usr/bin/env bash

{

bic() {
    for cmd in "$@"; do
        brew install -q --cask "$cmd"
    done
}

core_install() {
    brew install -q curl wget trash tree unzip coreutils  gum bash

    cmd_check curl wget trash tree unzip gum
}

essential_install() {
    slog "Installing Essential packages"

    core_install
    webi_install
    mise_install

    bis gawk p7zip cmake unar zip

    slog "Essential packages installation done!"

    cmd_check awk tmux cmake unar zip
}

cli_install() {
    bis tmux pkg-config urlview
    bi zsh-syntax-highlighting zsh-autosuggestions
    bi golang rust ripgrep neovim neovide luarocks lazydocker
    bi starship gping broot mcfly jq

    gh extension install github/gh-copilot

    cmd_check go rustc rg nvim neovide lazydocker starship gping broot mcfly jq
}

fonts_install() {
    bic font-jetbrains-mono-nerd-font font-monaspace-nerd-font font-caskaydia-mono-nerd-font
}

cpp_install() {
    slog "Installing C++"

    brew install -q cmake boost catch2 ccache cppcheck pre-commit

    slog "C++ installation done!"
}

virt_install() {
    slog "Installing virtualization packages"

    softwareupdate --install-rosetta --agree-to-license
    brew install -q podman
    bic podman-desktop
    brew install -q colima
    # podman machine set --rootful
    # sudo /opt/homebrew/Cellar/podman/4.9.2/bin/podman-mac-helper install

    dir_exists /Applications/Docker.app || brew install -q --cask docker

    slog "Virtualization packages installation done!"
}

python_uv_install() {
    curl -LsSf https://astral.sh/uv/install.sh | sh
}

pyenv_mac_install() {
    slog "Installing pyenv"
    brew install -q pyenv
    brew install -q pyenv-virtualenv
}

}
