#! /usr/bin/env bash

{

core_install() {
    brew install -q curl wget trash tree unzip coreutils
}

essential_install() {
    slog "Installing Essential packages"

    core_install
    webi_install
    mise_install

    brew install -q gawk tmux pkg-config urlview p7zip cmake unar zip
    brew install -q zsh-syntax-highlighting zsh-autosuggestions gum

    slog "Essential packages installation done!"
}

cli_install() {
    brew install -q golang rust

    brew install -q fzf ripgrep fd bat eza bottom gh nushell
    brew install -q neovim lazygit neovide luarocks gdu lazydocker
    brew install -q p7zip zoxide ShellCheck shfmt git-extras gawk
    brew install -q git-delta dust choose sd procs xh starship lsd cheat curlie

    brew install -q gping procs hyperfine duf broot mcfly jq
    brew install -q tldr doggo glances gtop httpie

    gh extension install github/gh-copilot
    alias gdu=gdu-go
}

fonts_install() {
    brew install -q --cask font-jetbrains-mono-nerd-font
    brew install -q --cask font-monaspace-nerd-font
}

cpp_install() {
    slog "Installing C++"

    brew install -q cmake boost catch2 ccache cppcheck pre-commit

    slog "C++ installation done!"

}

virt_install() {
    slog "Installing virtualization packages"

    softwareupdate --install-rosetta --agree-to-license
    brew install -q podman
    brew install -q --cask podman-desktop
    brew install -q colima
    # podman machine set --rootful
    # sudo /opt/homebrew/Cellar/podman/4.9.2/bin/podman-mac-helper install

    dir_exists /Applications/Docker.app || brew install -q --cask docker

    slog "Virtualization packages installation done!"
}

python_uv_install() {
    curl -LsSf https://astral.sh/uv/install.sh | sh
}

pyenv_mac_install() {
    slog "Installing pyenv"
    brew install -q pyenv
    brew install -q pyenv-virtualenv
}

}
