#! /usr/bin/env bash

{

source <(curl -s https://dub.sh/z3pTnAK)

main() {
    slog "Install xcode"
    xcode-select --install

    brew_install

    essential_install
    cpp_install
}

is_mac || err_exit "This script works only on macos. Quitting."

bootstrap "Macos setup"

}
