#! /usr/bin/env bash

{

source <(curl -s https://raw.githubusercontent.com/pervezfunctor/dotfiles/master/scripts/utils)

apps_install() {
    brew install --cask telegram
    brew install --cask zoom
    brew install --cask jetbrains-toolbox
    brew install --cask google-chrome
    brew install --cask zed
    brew install deluge
    brew install visual-studio-code
}

main() {
    slog "Install xcode"
    xcode-select --install

    brew_install

    essential_install
    cpp_install
    neovim_install
    pnpm_install

    apps_install

    dotfiles_install
    zsh_config_install
    tmux_config_install
}

is_mac || err_exit "This script works only on macos. Quitting."

bootstrap "Macos setup"

}
