#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

ui_install() {
    brew install -q github warp
    brew install -q --cask telegram
    brew install -q --cask zoom
    brew install -q --cask jetbrains-toolbox
    brew install -q --cask google-chrome
    brew install -q --cask zed
    brew install -q --cask wezterm
    brew install -q --cask microsoft-remote-desktop
    brew install -q deluge
    brew install -q visual-studio-code
}

main() {
    slog "Install xcode"
    xcode-select --install

    brew_install

    essential_install
    dotfiles_install

    cli_install
    fonts_install

    pnpm_install
    cpp_install
    pyenv_mac_install
    anaconda_install

    ui_install
    virt_install

    config_install
}

is_mac || err_exit "This script works only on macos. Quitting."

bootstrap "Macos setup"

}
