#! /usr/bin/env bash

{

export DEBIAN_FRONTEND=noninteractive

if command -v apt-get > /dev/null; then
    sudo apt-get -qq -y install curl sudo
else
    echo "apt-get not found. Quitting."
    exit 1
fi

si() {
    for p in "$@"; do
      slog "Installing package $p"
      sudo apt-get -qq -y install "$p"
    done
}

pacstall_install() {
    has_cmd pacstall && return 1

    sudo bash -c "$(curl -fsSL https://pacstall.dev/q/install)"
}

update_packages() {
    slog "Updating"

    if ! { sudo apt-get -qq update && sudo apt-get -qq upgrade -y; }; then
      err_exit "apt-get update/upgrade failed, quitting"
    fi
}

core_install() {
    update_packages

    si software-properties-common apt-transport-https ca-certificates gpg
    si curl wget git-core trash-cli tree command-not-found
    si tar unzip cmake build-essential stow libfuse2 zstd
}

sys_python_install() {
    slog "Installing python"

    si python3 python3-venv python3-virtualenv python3-pip python3-setuptools
    si python3-wheel python-is-python3 pipx

    pipx install uv

    slog "Python installation done!"

    cmd_check uv
}

snap_install() {
    has_cmd snap && return 0

    slog "Installing snap..."
    si snapd
    sudo snap install core

    slog "snap installation done!"
}

essential_install() {
    slog "Installing essential packages"

    core_install
    # mise_install
    sys_python_install
    pacstall_install
    is_ubuntu && snap_install

    si zip unar micro nala p7zip
    si libreadline-dev libsqlite3-dev libffi-dev libbz2-dev liblzma-dev

    slog "Essential packages installation done!"
}

# sudo apt-get -qq -y install \
#   build-essential pkg-config autoconf bison clang rustc \
#   libssl-dev libreadline-dev zlib1g-dev libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev libjemalloc2 \
#   libvips imagemagick libmagickwand-dev mupdf mupdf-tools gir1.2-gtop-2.0 gir1.2-clutter-1.0 \
#   redis-tools sqlite3 libsqlite3-0 libmysqlclient-dev libpq-dev postgresql-client postgresql-client-common wl-clipboard

cli_install() {
    si gawk tmux pkg-config urlview gh shellcheck zsh git just htop
    si sd lsd gdu bat hyperfine fd-find fzf ripgrep zoxide shfmt tree-sitter-cli

    gh extension install github/gh-copilot
}

cpp_install() {
    slog "Installing C++"

    si gcc gdb g++ libboost-all-dev catch2
    si clang llvm clang-tidy clang-format clang-tools libclang-dev
    si doxygen graphviz ccache cppcheck pre-commit
    si valgrind systemtap ltrace strace lldb lld

    cmake_install
    conan_install

    cmd_check gcc g++ gdb clang clang-tidy clang-format
    cmd_check cmake conan

    slog "C++ installation done!"
}

vscode_bin_install() {
    has_cmd code && return 0

    if ! grep -q "https://packages.microsoft.com/repos/code stable main" /etc/apt/sources.list.d/vscode.list; then
        echo "code code/add-microsoft-repo boolean true" | sudo debconf-set-selections

        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg

        echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null

        rm -f packages.microsoft.gpg
    fi

    sudo apt-get -qq update
    si code

    vscode_extensions_install

    cmd_check code
}

ui_install() {
    si chromium-browser virt-manager gnome-keyring xsel xclip wl-clipboard

    vscode_bin_install
    flathub_install
    apps_install
}

cockpit_install() {
    has_cmd cockpit && return 1

    slog "Installing cockpit"

    si cockpit cockpit-machines cockpit-sosreport cockpit-pcp cockpit-podman cockpit-storaged
    sudo systemctl enable --now cockpit.socket

    slog "cockpit installation done!"
}

podman_install() {
    si podman podman-toolbox podman-compose

    cmd_check podman
}

vm_install() {
    si libvirt-daemon
    sudo systemctl enable --now libvirtd
}

incus_install() {
    si incus
    incus_config_install
}

ct_install() {
    incus_install
    docker_install
    portainer_install
    podman_install
    cockpit_install

    si buildah distrobox
}

virt_install() {
    ct_install
    vm_install

    code_server_install
}

}
