#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

gtk_cursor_theme() {
    gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
}

rpm_ostree_packages_install() {
    sudo rpm-ostree -q install -y gnome-keyring g++ cmake gcc glibc-devel make stow zsh libvirt libvirt-daemon libvirt-daemon-config-network libvirt-daemon-driver-interface libvirt-daemon-driver-network libvirt-daemon-driver-nwfilter libvirt-daemon-driver-qemu libvirt-daemon-driver-secret libvirt-daemon-driver-storage-core
}

vscode_flatpak_install() {
    fpi com.visualstudio.code
    fpi com.visualstudio.code.tool.podman
    alias code="flatpak run com.visualstudio.code"
    cat $DOT_DIR/extras/vscode/extensions/common | xargs -L 1 flatpak run com.visualstudio.code --install-extension
}

nix_install() {
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --determinate
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

    nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    # nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    nix-channel --update
    # nix-shell '<home-manager>' -A install
    nix-env -iA nixpkgs.gtop
}

main() {
    appman_install
    mise_install

    mise_shell_install
    amm_shell_install

    smd ~/.local/share/fonts
    jetbrains_nerd_font_install

    flathub_install
    vscode_flatpak_install
    apps_install

    dotfile_install
    config_install
}

is_linux || err_exit "This script is only for Linux"

bootstrap "Immutable OS"

}
