#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

gtk_cursor_theme() {
    gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
}

rpm_ostree_packages_install() {
    sudo rpm-ostree -q install -y gnome-keyring g++ cmake gcc glibc-devel make stow zsh luarocks
    # autoconf automake binutils bison flex gcc gcc-c++ gdb glibc-devel libtool make pkgconf strace
}

home_manager_install() {
    nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    nix-channel --update
    nix-shell '<home-manager>' -A install
}

nix_install() {
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --determinate
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
}

main() {
    has_cmd git || err_exit "git not installed! Qutting."

    dotfiles_install

    micro_install
    appman_install
    mise_install

    mise_shell_install
    amm_shell_install

    smd ~/.local/share/fonts
    jetbrains_nerd_font_install

    flathub_install
    vscode_flatpak_install
    apps_install

    config_install
}

is_std_atomic || err_exit "This script is only for Atomic"

bootstrap "Immutable OS"

}
