#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    if has_cmd brew; then
        ujust aurora-cli
        bi neovim stow
        astronvim_install
    else
        warn "brew not installed; skipping shell utilities installation"
    fi

    if has_cmd flatpak; then
        fpi org.telegram.desktop
        fpi org.deluge_torrent.deluge
        fpi us.zoom.Zoom
        fpi md.obsidian.Obsidian
    else
        warn "flatpak not installed; skipping apps instalation"
    fi

    if has_cmd code; then
        vscode_extensions_install
        vscode_config_install
    else
        warn "code not installed; skipping vscode configuration"
    fi

    if has_cmd git; then
        dotfile_install

        if has_cmd stow; then
            config_install
        else
            warn "stow not installed; skipping configuration"
        fi
    else
        warn "git not installed skipping dotfiles"
    fi

    mise_install
    appman_install
}

is_aurora || err_exit "This script is only for Aurora"

bootstrap "Aurora OS"

}
