#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

brew_setup() {
    if ! has_cmd brew; then
        warn "brew not installed; skipping shell utilities installation."
        return 1
    fi

    brew_shell_slim_install
    bis emacs
}

apps_setup() {
    if ! has_cmd flatpak; then
        warn "flatpak not installed; skipping apps installation"
        return 1
    fi

    apps_slim_install
}

code_setup() {
    if ! has_cmd code; then
        warn "code not installed; skipping vscode configuration"
        return 1
    fi

    vscode_extensions_install
    vscode_config_install
}

config_setup() {
    if ! dir_exists "$DOT_DIR"; then
        warn "$DOT_DIR doesn't exist, skipping configuration"
        return 1
    fi

    if ! has_cmd stow; then
        warn "stow not installed, skipping configuration"
        return 1
    fi

    stowdf wallpapers
    share_config_install
    bin_config_install
    bash_config_install
    has_cmd zsh && zsh_config_install
    has_cmd nvim && nvim_config_install
    has_cmd tmux && tmux_config_install
    has_cmd emacs && stowdf emacs-slim
}

distrobox_setup() {
    if ! has_cmd distrobox; then
        warn "distrobox not installed, skipping distrobox creation"
        return 1
    fi

    source_dotfile fns
    distrobox_ublue_all
}

main() {
    dotfiles_install
    brew_setup
    apps_setup
    code_setup
    mise_install
    config_setup
}

is_aurora || is_bluefin || err_exit "This script is only for Aurora/Bluefin"

has_cmd git || err_exit "git not installed! Qutting."

bootstrap "uBlue OS"

}
