#! /usr/bin/env bash

{

source <(curl -sSL https://dub.sh/z3pTnAK)

main() {
    if has_cmd git; then
        dotfiles_install
    else
        warn "git not installed, cannot clone dotfiles and setup configuration on your system. Moving on to installing packages"
    fi

    if has_cmd brew; then
        brew_shell_essential_install
        slog "Installing terminal only emacs, for GUI, use flatpak"
        bis emacs
    else
        warn "brew not installed; skipping shell utilities installation."
    fi

    if has_cmd flatpak; then
        fpi org.telegram.desktop
        fpi org.deluge_torrent.deluge
        fpi us.zoom.Zoom
        fpi md.obsidian.Obsidian
    else
        warn "flatpak not installed; skipping apps installation"
    fi

    if has_cmd code; then
        vscode_extensions_install
        vscode_config_install
    else
        warn "code not installed; skipping vscode configuration"
    fi

    mise_install

    if dir_check "$DOT_DIR"; then
        warn "$DOT_DIR doesn't exist, skipping configuration"
    elif has_cmd stow; then
        stowdf wallpapers
        share_config_install
        bin_config_install
        bash_config_install
        has_cmd zsh && zsh_config_install
        has_cmd nvim && nvim_config_install
        has_cmd tmux && tmux_config_install
        has_cmd emacs && stowdf emacs-slim
    else
        warn "stow not installed, skipping configuration"
    fi
}

is_aurora || is_bluefin || err_exit "This script is only for Aurora"

bootstrap "uBlue OS"

}
